### ISSUE TITLE
v3.2.0 tag is missing

### ISSUE THREAD

**Issue by herb-kuta-lge** [NVIDIA/nvidia-container-runtime#102]
The last one [here](https://github.com/NVIDIA/nvidia-container-runtime/releases) is v3.1.4 (and v3.1.0 is marked as _Latest release_) but I see v3.2.0 listed in the [changelog](https://github.com/NVIDIA/nvidia-container-runtime/blob/master/debian/changelog).

**Comment by klueska** [comment]
Yes, we are aware of the inconsistency. There are also missing tags for some of the other components that make up `nvidia-docker`. We will be updating / tagging these repos appropriately soon.

**Comment by klueska** [comment]
This tag has now been added and a release has been published from it.
