### ISSUE TITLE
RHEL 7.8 unsupported

### ISSUE THREAD

**Issue by xuhdev** [NVIDIA/nvidia-container-runtime#106]
The URL: https://nvidia.github.io/nvidia-container-runtime/rhel7.8/nvidia-container-runtime.repo shows the distribution is unsupported, but https://nvidia.github.io/nvidia-container-runtime/rhel7.7/nvidia-container-runtime.repo works.

**Comment by klueska** [comment]
NVIDIA does not officially support 7.8 yet (because we don't test on it yet). We will only add a repo or 7.8 once it is officially supported, but I wouldn't be surprised if installing from 7.7 works without modification.
