### ISSUE TITLE
Downgrading from nvidia-container-runtime 1.0.1-dev to nvidia-container-runtime 1.0.0

### ISSUE THREAD

**Issue by yosefyehoshua** [NVIDIA/nvidia-container-runtime#116]
Hi, I'm trying to downgrade my nvidia-container-runtime version from 1.0.1-dev to 1.0.0 to get my docker machine work properly. 

typing:

`user1@user-linux:~$ sudo apt-get install nvidia-container-runtime=1.0.0 `

prints:

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Version '1.0.0' for 'nvidia-container-runtime' was not found
```
Any idea why 'version was not found'?

many thanks

**Comment by elezar** [comment]
Hi @yosefyehoshua I am closing this issue since the `1.*` version of `nvidia-container-runtime` is no longer being supported. If you have similar issues with the later versions of the `nvidia-container-runtime` or `nvidia-container-toolkit` packages please feel free to reopen.
