### ISSUE TITLE
NVIDIA_VISIBLE_DEVICES= does not work with device index

### ISSUE THREAD

**Issue by xunleiwu** [NVIDIA/nvidia-container-runtime#117]
Hello,

I have a machine with below two P100's.

(base) xunlwu@asttst01 ~]$nvidia-smi -L
GPU 0: Tesla V100-PCIE-16GB (UUID: GPU-id0)
GPU 1: Tesla V100-PCIE-16GB (UUID: GPU-id1)

I would like to create a pod using GPU 1 (the second GPU) specifically. According to the OCI-spec documentation
https://github.com/NVIDIA/nvidia-container-runtime#environment-variables-oci-spec

> NVIDIA_VISIBLE_DEVICES
> This variable controls which GPUs will be made accessible inside the container.
> 
> Possible values
> 0,1,2, GPU-fef8089b …: a comma-separated list of GPU UUID(s) or index(es).
> ...

NVIDIA_VISIBLE_DEVICES=1 or NVIDIA_VISIBLE_DEVICES=GPU-id1 should be equivalent. However, the deployment with "NVIDIA_VISIBLE_DEVICES=1" won't start at all. "NVIDIA_VISIBLE_DEVICES=GPU-id1" behaves as expected.

Would you please help? Thank you.

**Comment by klueska** [comment]
This is unexpected. Can you clarify what you mean by "won't start at all"?

**Comment by xunleiwu** [comment]
Hi @klueska,
The deployment never comes up after 15min despite the resource name is registered. When deploying with NVIDIA_VISIBLE_DEVICES=GPU-id in the manifest yaml file, the pod comes right up with proper GPU device claimed.

**Comment by xunleiwu** [comment]
I tested on 2 GPU boxes specifying the 2nd GPU. I did not try the 1st GPU just in case there is any default logic picking up the first one.

**Comment by klueska** [comment]
Im not quite following your workflow. It sounds like you are running on Kubernetes and specifying a GPU via the nvidia.com/gpu resource type? But then you are also trying to set NVIDIA_VISIBLEDEVICES? The two are not compatible with one another. You can only use one method or the other, bot both.

**Comment by xunleiwu** [comment]
Hi @klueska,
I understand setting NVIDIA_VISIBLE_DEVICES would overwrite whatever it is in the resources/requests section. The issue is that the container won't start when specifying NVIDIA_VISIBLE_DEVICES=1 environment var in the manifest no matter I have nvidia.com/gpu: in resources/requests section or not. Replacing it with NVIDIA_VISIBLE_DEVICES=GPU-id on the other hand works as documented.

**Comment by klueska** [comment]
That is incorrect.  NVIDIA_VISIBLE_DEVICES will not overwrite whatever it is in the resources/requests section. Setting NVIDIA_VISIBLE_DEVICES will only work if no `nvidia.com/gpu` resources are defined.  It's a bit of a hack though, because it basically bypasses the plugin and forces an allocation of the GPU unbeknowst to kubernetes.

Regarding:
> The issue is that the container won't start when specifying NVIDIA_VISIBLE_DEVICES=1 environment var in the manifest no matter I have nvidia.com/gpu: in resources/requests section or not

This is unexpected and highly suspicious. Something must be weird in your setup because I can't imagine how doing nothing other than setting an ENVVAR would cause the deployment to block.

Can you give me more details about your pod spec and the output of `kubectl describe node` on the node that has your GPUs on it.

**Comment by elezar** [comment]
@xunleiwu I am closing this issue as out of date. If this problem is still present, please reopen this issue and provide the information requested by @klueska in his last comment.
