### ISSUE TITLE
Disable kmem for nvidia-container-runtime

### ISSUE THREAD

**Issue by zionwu** [NVIDIA/nvidia-container-runtime#118]
We are hitting the kmem issue(https://github.com/kubernetes/kubernetes/issues/70324 and https://github.com/opencontainers/runc/pull/1921) on GPU host. 

On GPU host, we use nvidia-container-runtime instead of runc.  We need to re-compile it with `nokmem` option.  However, we can't find the related code in this repo.  
The version of nvidia-container-runtime is 1.0.0-rc8:
![image](https://user-images.githubusercontent.com/1213386/93308785-4999e900-f835-11ea-93cb-c8d3cbe65d0b.png)

Does anyone know where is the code for nvidia-container-runtime  1.0.0-rc8?

**Comment by zionwu** [comment]
I found this PR https://github.com/NVIDIA/nvidia-container-runtime/pull/64
Is this the change I need to make on top of  runc 1.0.0-rc8?

**Comment by zionwu** [comment]
@RenaudWasTaken Could you please help to confirm that this PR https://github.com/NVIDIA/nvidia-container-runtime/pull/64 is the code added to runc for nvidia-container-runtime 1.0.0-rc8?

**Comment by klueska** [comment]
May I ask why you are using such an old version of `nvidia-container-runtime`?
As of `v3.0.0` the `nvidia-container-runtime` is no longer a fork of `runC`, but rather a shim on top of it.
That way you can use whatever version of `runC` you require and know that the `nvidia-container-runtime` will shell out to it after simply injecting the necessary runtime hook into the `runC` spec.

**Comment by klueska** [comment]
Actually, looking more closely at this, the version you are seeing there is actually from `runC` and not from `nvidia-container-runtime`. Can you tell me the package version of `nvidia-container-runtime` from `apt` or `yum` that you have (depending on which system you are running on).
```

```

**Comment by zionwu** [comment]
> Can you tell me the package version of `nvidia-container-runtime`

We are using CentOS 7.4 and using the following rpm to install:
```
libnvidia-container1-1.0.5-1.x86_64.rpm
libnvidia-container-tools-1.0.5-1.x86_64.rpm
nvidia-container-runtime-2.0.0-3.docker18.09.7.x86_64.rpm
nvidia-container-toolkit-1.0.5-2.x86_64.rpm
nvidia-docker2-2.0.3-3.docker18.09.7.ce.noarch.rpm

```

The version I showed is the result of running `nvidia-container-runtime --version`. 
I found out that older nvidia-container-runtime is a fork of runc with the change in this PR:https://github.com/NVIDIA/nvidia-container-runtime/pull/64/files. 

Actually you can find these patch from the older commit of this repos: 
https://github.com/NVIDIA/nvidia-container-runtime/blob/03af0a80dbcbcfa09a828cde46151749bee2480e/runtime/runc/3f2f8b84a77f73d38244dd690525642a72156c64/0001-Add-prestart-hook-nvidia-container-runtime-hook-to-t.patch

I already made the same change to runc 1.0.0-rc8 and use `make BUILDTAGS="seccomp nokmem"` to build a new binary.
