### ISSUE TITLE
support for arch based distros

### ISSUE THREAD

**Issue by nspeer12** [NVIDIA/nvidia-container-runtime#120]
Support for arch based distros like Manjaro would be greatly appreciated.

**Comment by nspeer12** [comment]
Installing from source using yay failed for me. After a few attempts, using the prebuilt binaries works fine.

**Comment by PlugInRichi** [comment]
Could you explain how you made it in more detail? I'm trying to install in Arch 
Thanks!

**Comment by PlugInRichi** [comment]
> Installing from source using yay failed for me. After a few attempts, using the prebuilt binaries works fine.

Could you explain how you made it in more detail? I'm trying to install in Arch
Thanks!

> Installing from source using yay failed for me. After a few attempts, using the prebuilt binaries works fine.

Could you explain how you made it in more detail? I'm trying to install in Arch
Thanks!
