### ISSUE TITLE
[Ubuntu 20.04] Setup installs repository for Ubuntu 18.04

### ISSUE THREAD

**Issue by ahiiti** [NVIDIA/nvidia-container-runtime#122]
When you conrigure the repository as in https://nvidia.github.io/nvidia-container-runtime/#debian-based-distributions in ubuntu 20.04, actually the repository sources for ubuntu 18.04 are installed.

### Reproduction

Get distribution identifier:

    $ distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
    $ echo $distribution
    ubuntu20.04

Download repository list:

    $ curl https://nvidia.github.io/nvidia-container-runtime/$distribution/nvidia-container-runtime.list
    deb https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/$(ARCH) /
    #deb https://nvidia.github.io/libnvidia-container/experimental/ubuntu18.04/$(ARCH) /
    deb https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/$(ARCH) /
    #deb https://nvidia.github.io/nvidia-container-runtime/experimental/ubuntu18.04/$(ARCH) /

**Comment by klueska** [comment]
This is expected. The repo for Ubuntu 20.04 is just a symlink to the 18.04 repo.
You can see it the layout here: https://github.com/NVIDIA/nvidia-container-runtime/tree/gh-pages/stable
