### ISSUE TITLE
Jetson: nvidia-container-runtime tries to mount /dev/nvidiactl

### ISSUE THREAD

**Issue by mildsunrise** [NVIDIA/nvidia-container-runtime#123]
JetPack has this file: `/etc/nvidia-container-runtime/host-files-for-container.d/l4t.csv`
Which specifies:

~~~
dev, /dev/nvidiactl
~~~

And it seems to be preventing the container from starting, because the device doesn't exist:

~~~
nvidia-container-cli: mount error: stat failed: /dev/nvidiactl: no such file or directory
~~~

Should it exist? The file comes from the `nvidia-l4t-init` package.

**Comment by mildsunrise** [comment]
This occurs on a freshly installed Xavier with full JetPack.

**Comment by timorkal** [comment]
getting this also, please check.

**Comment by elezar** [comment]
@mildsunrise sorry for the delay in getting to you. The CSV files contain devices / files which may not be present on all Tegra variants. The NVIDIA runtime is supposed to handle these missing devices / libraries gracefully. If this is not happening, could you please provide more information on the behaviour that you're seeing.

On my nano I have the following:
```
~$ cat /etc/nvidia-container-runtime/host-files-for-container.d/l4t.csv | grep /dev/nvidiactl
dev, /dev/nvidiactl
```
and when enabling debug logging in `/etc/nvidia-container-runtime/config.toml` by uncommenting the `#debug = ` lines, the `/var/log/nvidia-container-toolkit.log` file shows:
```
W0709 10:03:49.495791 8550 nvc_info.c:459] missing device /dev/nvidiactl
```
but execution continues.

**Comment by elezar** [comment]
@mildsunrise @timorkal are you still experiencing this issue. Looking at the issue again, it may be that you are using a version of the `nvidia-container-cli` (`libnvidia-container-tools` package) that is not intended for use on Jetson devices.

Also see https://github.com/NVIDIA/libnvidia-container/issues/135#issuecomment-981704944 regarding the 1.7.0-rc.1 release of the NVIDIA Container Toolkit that has better packaging support for Jetson.

I'm going to close this issue for the time being, but feel free to reopen it if you're still having problems. In this case please provide information on the package versions that are installed on your respective systems.
