### ISSUE TITLE
Jetson: libnvdla_compiler.so not passed

### ISSUE THREAD

**Issue by mildsunrise** [NVIDIA/nvidia-container-runtime#124]
For some jetpack distributions (i.e. Xavier but not Nano), `libnvinfer.so.7` depends on `libnvdla_compiler.so`:

~~~
$ ldd /usr/lib/aarch64-linux-gnu/libnvinfer.so.7
        linux-vdso.so.1 (0x0000007f8b58f000)
        libcublas.so.10 => /usr/lib/aarch64-linux-gnu/libcublas.so.10 (0x0000007f79425000)
        libcudart.so.10.2 => /usr/local/cuda-10.2/lib64/libcudart.so.10.2 (0x0000007f793b1000)
        libcudnn.so.8 => /usr/lib/aarch64-linux-gnu/libcudnn.so.8 (0x0000007f79373000)
        libmyelin.so.1 => /usr/lib/aarch64-linux-gnu/libmyelin.so.1 (0x0000007f78ee5000)
        libnvrtc.so.10.2 => /usr/local/cuda-10.2/lib64/libnvrtc.so.10.2 (0x0000007f77ab4000)
        libdl.so.2 => /lib/aarch64-linux-gnu/libdl.so.2 (0x0000007f77a7a000)
        libnvdla_compiler.so => /usr/lib/aarch64-linux-gnu/tegra/libnvdla_compiler.so (0x0000007f77646000)
        libnvmedia.so => /usr/lib/aarch64-linux-gnu/tegra/libnvmedia.so (0x0000007f775df000)
        libEGL.so.1 => /usr/lib/aarch64-linux-gnu/libEGL.so.1 (0x0000007f775be000)
        libstdc++.so.6 => /usr/lib/aarch64-linux-gnu/libstdc++.so.6 (0x0000007f7742a000)
        libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000007f77371000)
        libgcc_s.so.1 => /lib/aarch64-linux-gnu/libgcc_s.so.1 (0x0000007f7734d000)
        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000007f771f4000)
        /lib/ld-linux-aarch64.so.1 (0x0000007f8b563000)
        libcublasLt.so.10 => /usr/lib/aarch64-linux-gnu/libcublasLt.so.10 (0x0000007f7522e000)
        libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000007f75202000)
        librt.so.1 => /lib/aarch64-linux-gnu/librt.so.1 (0x0000007f751eb000)
        libnvos.so => /usr/lib/aarch64-linux-gnu/tegra/libnvos.so (0x0000007f751cd000)
        libnvrm.so => /usr/lib/aarch64-linux-gnu/tegra/libnvrm.so (0x0000007f7518a000)
        libnvrm_graphics.so => /usr/lib/aarch64-linux-gnu/tegra/libnvrm_graphics.so (0x0000007f7516a000)
        libnvdc.so => /usr/lib/aarch64-linux-gnu/tegra/libnvdc.so (0x0000007f7514b000)
        libnvtvmr.so => /usr/lib/aarch64-linux-gnu/tegra/libnvtvmr.so (0x0000007f750bb000)
        libnvparser.so => /usr/lib/aarch64-linux-gnu/tegra/libnvparser.so (0x0000007f7507f000)
        libGLdispatch.so.0 => /usr/lib/aarch64-linux-gnu/libGLdispatch.so.0 (0x0000007f74f53000)
        libnvimp.so => /usr/lib/aarch64-linux-gnu/tegra/libnvimp.so (0x0000007f74f3e000)
~~~

The `nvidia-container-csv-tensorrt` package installs definitions to pass `libnvinfer.so.7` but we don't see `libnvdla_compiler.so` being specified anywhere, so our applications fail.

**Comment by mildsunrise** [comment]
Sorry, this probably belonged somewhere else... if you have some better idea of where to report it, it would be appreciated :)

**Comment by codethief** [comment]
We've ran into the same issue. In fact, on the Jetson Xavier NX `libnvinfer.so` also depends on `libnvmedia.so`, whereas on the Jetson Nano it does not.

**Comment by codethief** [comment]
@twmht I'm currently not working on Nvidia stuff (and won't be in the foreseeable future), so I'm afraid I don't know the answer to your question.

**Comment by mildsunrise** [comment]
> Question: I'm assuming that this is for containerized applications?

Yes

> My assumption is that the library `libnvdla_compiler.so` is not present in the CSV files at `/etc/nvidia-container-runtime/host-files-for-container.d`.

Yes, that's exactly why I opened the issue

**Comment by klueska** [comment]
The components that make up the NVIDIA container stack only serve to parse the CSV files provided on a platform. We do not maintain the contents of the CSV files provided by each platform. It is up to the platform maintainer to decide which libs/devs/bins, etc. to include in the CSVs files provided for their platform.

The better place to report this issue would therefore likely be here:
https://forums.developer.nvidia.com/c/agx-autonomous-machines/jetson-embedded-systems/70

**Comment by mildsunrise** [comment]
I think I didn't report it in the end, sorry. posting this in case someone else wants to do it
