### ISSUE TITLE
Provide static release artifacts

### ISSUE THREAD

**Issue by Sh4d1** [NVIDIA/nvidia-container-runtime#126]
Hello!

It would be nice if static binaires were provided with the releases

**Comment by hpcpony** [comment]
I second this (better yet provide nvidia-container-cli with the standard NVIDIA cuda install):

I found that changing the Makefile line:

```BIN_LDLIBS         = -l:$(LIB_SHARED) -lcap $(LDLIBS)```

to

```BIN_LDLIBS         = $(LIB_STATIC) -lcap $(LDLIBS) -ldl -lseccomp```

is sufficient to get rid of the dynamic libnvidia-container.so which is the biggest annoyance.

The reason I find this useful is I can take the "static" version and place it in my charliecloud bin and not have to worry about adding additional paths to find a separate nvidia-container-cli (and the dynamic library).

**Comment by hpcpony** [comment]
Got this is in the wrong place.  Sorry.

**Comment by elezar** [comment]
Hi @Sh4d1. Do you mean that these should be available on GitHub, or do you mean "Statically-linked" binaries?

**Comment by elezar** [comment]
We don't currently have the capacity to also include static binaries in our releases. It is something that we are aware of and may be realizable once we only support CDI.
