### ISSUE TITLE
Why is there no memory setting?

### ISSUE THREAD

**Issue by NJ2046** [NVIDIA/nvidia-container-runtime#128]
Specifies the container runtime video memory Settings

**Comment by klueska** [comment]
I don’t quite understand. What is your question exactly?

**Comment by NJ2046** [comment]
docker run 
-m, --memory bytes                   Memory limit
nvidia-container-runtime
--runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=3

why is there no  
--runtime=nvidia -e NVIDIA_USE_MEMORY=user define size

**Comment by klueska** [comment]
Because three is no underlying mechanisms to constrain the amount of memory you are given access to on a GPU. Once you have acces to the GPU (via NVIDIA_VISIBLE_DEVICES) you have access to all of its memory.

**Comment by NJ2046** [comment]
thank you very much.I'm going to restrict it in my code.
