### ISSUE TITLE
Issues installing nvidia-container-runtime

### ISSUE THREAD

**Issue by Knowlue** [NVIDIA/nvidia-container-runtime#13]
Trying to install the last dependency for nvidia docker 2 which is nvidia container runtime. Followed the steps for a Ubuntu install and after I call "sudo apt-get install nvidia-container-runtime" this is the error that I am getting: 

Reading package lists... Done
Building dependency tree
Reading state information... Done
Package nvidia-container-runtime is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'nvidia-container-runtime' has no installation candidate

Has anyone encountered this and figured out what went wrong?

**Comment by flx42** [comment]
Did you do `sudo apt-get update`? 
What is the content of `/etc/apt/sources.list.d/nvidia-docker.list`?

**Comment by flx42** [comment]
Or `/etc/apt/sources.list.d/nvidia-container-runtime.list`

**Comment by Knowlue** [comment]
I did.

Here's what the big block of text I got.

Reading package lists... Done
W: Target Packages (edge/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/docker.list:1
W: Target Translations (edge/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/docker.list:1
W: Target Translations (edge/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/docker.list:1
W: Target Packages (Packages) is configured multiple times in /etc/apt/sources.list.d/libnvidia-container.list:1 and /etc/apt/sources.list.d/nvidia-container-runtime.list:1
W: Target Translations (en_US) is configured multiple times in /etc/apt/sources.list.d/libnvidia-container.list:1 and /etc/apt/sources.list.d/nvidia-container-runtime.list:1
W: Target Translations (en) is configured multiple times in /etc/apt/sources.list.d/libnvidia-container.list:1 and /etc/apt/sources.list.d/nvidia-container-runtime.list:1
W: Target Packages (Packages) is configured multiple times in /etc/apt/sources.list.d/libnvidia-container.list:1 and /etc/apt/sources.list.d/nvidia-docker.list:1
W: Target Translations (en_US) is configured multiple times in /etc/apt/sources.list.d/libnvidia-container.list:1 and /etc/apt/sources.list.d/nvidia-docker.list:1
W: Target Translations (en) is configured multiple times in /etc/apt/sources.list.d/libnvidia-container.list:1 and /etc/apt/sources.list.d/nvidia-docker.list:1
W: Target Packages (Packages) is configured multiple times in /etc/apt/sources.list.d/nvidia-container-runtime.list:2 and /etc/apt/sources.list.d/nvidia-docker.list:2
W: Target Translations (en_US) is configured multiple times in /etc/apt/sources.list.d/nvidia-container-runtime.list:2 and /etc/apt/sources.list.d/nvidia-docker.list:2
W: Target Translations (en) is configured multiple times in /etc/apt/sources.list.d/nvidia-container-runtime.list:2 and /etc/apt/sources.list.d/nvidia-docker.list:2
W: Target Packages (edge/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/docker.list:1
W: Target Translations (edge/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/docker.list:1
W: Target Translations (edge/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/docker.list:1
W: Target Packages (Packages) is configured multiple times in /etc/apt/sources.list.d/libnvidia-container.list:1 and /etc/apt/sources.list.d/nvidia-container-runtime.list:1
W: Target Translations (en_US) is configured multiple times in /etc/apt/sources.list.d/libnvidia-container.list:1 and /etc/apt/sources.list.d/nvidia-container-runtime.list:1
W: Target Translations (en) is configured multiple times in /etc/apt/sources.list.d/libnvidia-container.list:1 and /etc/apt/sources.list.d/nvidia-container-runtime.list:1
W: Target Packages (Packages) is configured multiple times in /etc/apt/sources.list.d/libnvidia-container.list:1 and /etc/apt/sources.list.d/nvidia-docker.list:1
W: Target Translations (en_US) is configured multiple times in /etc/apt/sources.list.d/libnvidia-container.list:1 and /etc/apt/sources.list.d/nvidia-docker.list:1
W: Target Translations (en) is configured multiple times in /etc/apt/sources.list.d/libnvidia-container.list:1 and /etc/apt/sources.list.d/nvidia-docker.list:1
W: Target Packages (Packages) is configured multiple times in /etc/apt/sources.list.d/nvidia-container-runtime.list:2 and /etc/apt/sources.list.d/nvidia-docker.list:2
W: Target Translations (en_US) is configured multiple times in /etc/apt/sources.list.d/nvidia-container-runtime.list:2 and /etc/apt/sources.list.d/nvidia-docker.list:2
W: Target Translations (en) is configured multiple times in /etc/apt/sources.list.d/nvidia-container-runtime.list:2 and /etc/apt/sources.list.d/nvidia-docker.list:2

**Comment by flx42** [comment]
Ah yes, `/etc/apt/sources.list.d/nvidia-container-runtime.list` is a subset of `/etc/apt/sources.list.d/nvidia-docker.list`. And `apt` doesn't like that.

Please remove `/etc/apt/sources.list.d/nvidia-container-runtime.list` and `apt-get update` again.

**Comment by Knowlue** [comment]
Removed it. Here's what I get when I called * apt-get update *

W: Target Packages (edge/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/docker.list:1
W: Target Translations (edge/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/docker.list:1
W: Target Translations (edge/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/docker.list:1
W: Target Packages (Packages) is configured multiple times in /etc/apt/sources.list.d/libnvidia-container.list:1 and /etc/apt/sources.list.d/nvidia-docker.list:1
W: Target Translations (en_US) is configured multiple times in /etc/apt/sources.list.d/libnvidia-container.list:1 and /etc/apt/sources.list.d/nvidia-docker.list:1
W: Target Translations (en) is configured multiple times in /etc/apt/sources.list.d/libnvidia-container.list:1 and /etc/apt/sources.list.d/nvidia-docker.list:1
W: Target Packages (edge/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/docker.list:1
W: Target Translations (edge/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/docker.list:1
W: Target Translations (edge/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/docker.list:1
W: Target Packages (Packages) is configured multiple times in /etc/apt/sources.list.d/libnvidia-container.list:1 and /etc/apt/sources.list.d/nvidia-docker.list:1
W: Target Translations (en_US) is configured multiple times in /etc/apt/sources.list.d/libnvidia-container.list:1 and /etc/apt/sources.list.d/nvidia-docker.list:1
W: Target Translations (en) is configured multiple times in /etc/apt/sources.list.d/libnvidia-container.list:1 and /etc/apt/sources.list.d/nvidia-docker.list:1

Still wasn't able to install container runtime

**Comment by flx42** [comment]
Also remove `/etc/apt/sources.list.d/libnvidia-container.list`
Not sure what's up with your `docker.list` though

**Comment by Knowlue** [comment]
It's still leaving me with Package nvidia-container-runtime is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'nvidia-container-runtime' has no installation candidate

**Comment by flx42** [comment]
What's the content of `/etc/apt/sources.list.d/nvidia-docker.list` now?

**Comment by Knowlue** [comment]
deb https://nvidia.github.io/libnvidia-container/ubuntu16.04/amd64 /
deb https://nvidia.github.io/nvidia-container-runtime/ubuntu16.04/amd64 /
deb https://nvidia.github.io/nvidia-docker/ubuntu16.04/amd64 /

**Comment by flx42** [comment]
I think your setup is missed up, check everything you have in `/etc/apt/sources.list.d/`

**Comment by flx42** [comment]
@Knowlue any update?
