### ISSUE TITLE
apt-get: Unable to locate package nvidia-container-runtime

### ISSUE THREAD

**Issue by Julius-ZCJ** [NVIDIA/nvidia-container-runtime#130]
System: ubuntu16.04
Cuda: 10.1
GPU: Tesla P100-PCIE

I want to update GPU driver, first I update to 418, I get this error, I can't install nvidia-container-runtime, and when I run a container I got this error: docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]]

refer to https://collabnix.com/introducing-new-docker-cli-api-support-for-nvidia-gpus-under-docker-engine-19-03-0-beta-release/ they said this error due to nvidia driver, so I update driver to 430.64 but I get the same error

How I can fix this error? Anyone can help me?

**Comment by klueska** [comment]
Can you add a bit more information? It's unclear from your description what your exact environment is, and what the exact error in installing the driver was. For example, after you install the driver, are you able to run `nvidia-smi` on the host and see information about the GPUs installed on the system?  Also, it's unclear what you mean by "I can't install nvidia-container-runtime". What was the issue you encountered trying to install it?

**Comment by Julius-ZCJ** [comment]
Thank you for your reply, I have fixed this error
