### ISSUE TITLE
Is nvidia-container-runtime available for Windows and Mac

### ISSUE THREAD

**Issue by mianasbat** [NVIDIA/nvidia-container-runtime#133]
I was trying to run a [GPU docker container ](https://scikit-surgerydocker.readthedocs.io/en/latest/gpu_container.html)on windows 10 machine and I got the error 
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request: unknown.
```

Since the example works fine on Ubuntu 18.4 having Nvidia container runtime installed, I think it is not working on Windows because of absence of it. 

I havent tried it on Mac yet but my question is do you have nvidia-container-runtime for windows and mac because I couldnt find it.

Thanks

**Comment by klueska** [comment]
No. It's only supported on linux at the moment.
