### ISSUE TITLE
Getting "unsupported distribution" for Ubuntu repository package lists

### ISSUE THREAD

**Issue by azza-bazoo** [NVIDIA/nvidia-container-runtime#135]
I can't fetch URLs like these, I see the response below:

* https://nvidia.github.io/nvidia-container-runtime/ubuntu16.04/
* https://nvidia.github.io/nvidia-docker/ubuntu16.04/amd64/

```
# Unsupported distribution! # Check https://nvidia.github.io/nvidia-container-runtime
```

But I can still download packages directly, for example these work properly:

* https://nvidia.github.io/nvidia-docker/ubuntu16.04/amd64/nvidia-docker2_2.5.0-1_all.deb
* https://nvidia.github.io/nvidia-container-runtime/ubuntu18.04/amd64/nvidia-container-runtime_3.4.2-1_amd64.deb

**Comment by klueska** [comment]
Yes, there is no directory listing, so what you are seeing is the (unfortunate) result of getting back an non-useful 404.
