### ISSUE TITLE
error: "undefined symbol " when import "containerd" package

### ISSUE THREAD

**Issue by xiaozhouX** [NVIDIA/nvidia-container-runtime#137]
We have a Golang application use `gpu-monitoring-tools/bindings/go/nvml`.  After import `containerd` package, the application will shutdown and throw an error  `symbol lookup error`.

I write a sample, which trigger the same error:
```
package main

import (
	"github.com/NVIDIA/gpu-monitoring-tools/bindings/go/nvml"
	"github.com/containerd/containerd"
	
)

func main() {
	_, err := containerd.New(".....")
	if err != nil {
		println("containerd new err", err.Error())
		return
	}
	err = nvml.Init()
	if err != nil {
		println("nvml init err", err.Error())
		return
	}
	return
}
```
Then the error show up: 
`symbol lookup error: /app/test : undefined symbol: nvmlGpuInstanceGetComputeInstanceById`

Interestingly, if I remove `containerd` import, the error disappear.

**Comment by klueska** [comment]
Please don’t use those „bindings“, they are old and unmaintained and it’s unclear what sideffects could be run when using them.

Please use github.com/nvidia/go-nvml instead.

**Comment by xiaozhouX** [comment]
> Please don’t use those „bindings“, they are old and unmaintained and it’s unclear what sideffects could be run when using them.
> 
> Please use github.com/nvidia/go-nvml instead.

Thanks for reply, I use `github.com/NVIDIA/go-nvml/pkg/nvml` replace `github.com/NVIDIA/gpu-monitoring-tools/bindings/go/nvml`, appear the same error.

**Comment by elezar** [comment]
I am closing this issue since it was also posted as NVIDIA/go-nvml#18
