### ISSUE TITLE
Can you support custom configuration compute mode?

### ISSUE THREAD

**Issue by LinJinghua** [NVIDIA/nvidia-container-runtime#139]
Some users want the compute mode of the gpu card to be EXCLUSIVE_PROCESS, but some users want it to be DEFAULT. If the runtime can set the corresponding compute mode according to user-defined environment variables (such as NVIDIA_COMPUTE_MODE ), it would be great.

Do you have plans to support? :P

**Comment by klueska** [comment]
There are no plans to do that.
The container runtime does not initialize or setup the GPUs in any way. It only provides access to GPUs through cgroups permissions, but doesn't know (or care about) the actual properties of the GPUs it is giving access to.
