### ISSUE TITLE
The following signatures were invalid: EXPKEYSIG 6ED91CA3AC1160CD

### ISSUE THREAD

**Issue by fahadchauhan4** [NVIDIA/nvidia-container-runtime#144]
System: ubuntu 18.04

I was removing all Cuda Cudnn and Nvidia installations so that I can fresh install everything. but after deleting everything using commands: 
sudo apt-get remove --purge '^nvidia-.*'
sudo apt-get install ubuntu-desktop
sudo rm /etc/X11/xorg.conf
echo 'nouveau' | sudo tee -a /etc/modules

I did sudo apt update and this error occurred. I tried doing
curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -

this also didn't solve the issue.

Here is the error:
Err:13 https://nvidia.github.io/nvidia-container-runtime/experimental/ubuntu18.04/amd64  InRelease 
  The following signatures were invalid: EXPKEYSIG 6ED91CA3AC1160CD NVIDIA CORPORATION (Open Source Projects) <cudatools@nvidia.com>

**Comment by elezar** [comment]
Hi @fahadchauhan4. There was an issue with how our experimental repos were updated a while back that caused this. Since these are currently out of date (there are no packages there that have not already been released as `stable`), please uncomment or remove the `experimental` repos from any `nvidia` APT lists.

For example:
```
$ cat /etc/apt/sources.list.d/nvidia-docker.list
deb https://klueska.github.io/libnvidia-container/stable/ubuntu18.04/$(ARCH) /
# deb https://nvidia.github.io/libnvidia-container/experimental/ubuntu18.04/$(ARCH) /
deb https://klueska.github.io/nvidia-container-runtime/stable/ubuntu18.04/$(ARCH) /
# deb https://nvidia.github.io/nvidia-container-runtime/experimental/ubuntu18.04/$(ARCH) /
deb https://klueska.github.io/nvidia-docker/ubuntu18.04/$(ARCH) /
```
(note this is expected to only affect the `nvidia-container-runtime` repository).

**Comment by fahadchauhan4** [comment]
![Screenshot from 2021-07-09 17-45-44](https://user-images.githubusercontent.com/78346488/125079943-a1b01d80-e0dd-11eb-9998-6cc99783f28e.png)
these experimental repos were commented so I uncomment these two and ran sudo apt update but still same error.

**Comment by fahadchauhan4** [comment]
removing experimental repos from all nvidia-* files located in /etc/apt/sources.list.d/ fixed the error. 
Thank you for the help.
