### ISSUE TITLE
how can I install the nvidia-container-runtime offline?

### ISSUE THREAD

**Issue by JunMa11** [NVIDIA/nvidia-container-runtime#148]
Thanks for sharing the great tool.

My server environment is Ubuntu 18.04 and docker 20.10. The server can not access the network but I can upload files to it.

how can I install the nvidia-container-runtime offline?

Kindest regards,
Jun

**Comment by elezar** [comment]
Hi @JunMa11. You should be able to download the required Debian files required by `nvidia-docker2` including:

* `nvidia-docker2`
* `nvidia-container-runtime`
* `nvidia-container-toolkit`
* `libnvidia-container-tools`

And install them in reverse order using `dpkg` on the host.

**Comment by JunMa11** [comment]
Thanks for your help very much.
