### ISSUE TITLE
unable to install on Docker 

### ISSUE THREAD

**Issue by DominionSoftware** [NVIDIA/nvidia-container-runtime#15]
root@2c62044607a9:/# curl -s -L https://nvidia.github.io/nvidia-container-runtime/gpgkey |sudo apt-key add -
OK

root@2c62044607a9:/# curl -s -L https://nvidia.github.io/nvidia-container-runtime/ubuntu16.04/amd64/nvidia-container-runtime.list | sudo tee /etc/apt/sources.list.d/nvidia-container-runtime.list
deb https://nvidia.github.io/libnvidia-container/ubuntu16.04/amd64 /
deb https://nvidia.github.io/nvidia-container-runtime/ubuntu16.04/amd64 /

root@2c62044607a9:/# sudo apt-get update
Ign:1 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  InRelease
Hit:2 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release
Hit:3 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:5 http://archive.ubuntu.com/ubuntu xenial InRelease
Hit:6 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:7 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
0% [Working]

Just hangs on 0% [Working]

**Comment by flx42** [comment]
Try installing `apt-transport-https` and try again please.

**Comment by DominionSoftware** [comment]
seems to do the trick thanks.
