### ISSUE TITLE
Kubuntu 21.10

### ISSUE THREAD

**Issue by mbencherif** [NVIDIA/nvidia-container-runtime#158]
When is it possible to get the nvidia-docker for :

PRETTY_NAME="Ubuntu 21.10"
NAME="Ubuntu"
VERSION_ID="21.10"
VERSION="21.10 (Impish Indri)"
VERSION_CODENAME=impish
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=impish

Thanks

**Comment by elezar** [comment]
@mbencherif you should be able to install the `18.04` packages. One thing to check is whether `20.10` has cgroupv2 enabled by default, in which case additional configuration changes would be required (similar to Debian 11).

**Comment by mbencherif** [comment]
Many Thanks Elan,
I am working on Kubuntu 21.10
This workaround workded : https://github.com/NVIDIA/libnvidia-container/issues/111
Comment of : DimanNe commented on Oct 2 
1. Need to change :
/etc/nvidia-container-runtime/config.toml
no-cgroups = true
Append all devices , else it won't work...
docker run --rm --gpus all --device /dev/nvidia0 --device /dev/nvidiactl --device /dev/nvidia-modeset --device /dev/nvidia-uvm nvidia/cuda:11.0-base nvidia-smi

Many thanks...

**Comment by elezar** [comment]
@mbencherif thanks for confirming. Could we close this issue as the workaround is known?

**Comment by klueska** [comment]
We now have an RC of libnvidia-container out that adds support for `cgroupv2`.

If you would like to try it out, make sure and add the `experimental` repo to your apt sources and install the latest packages:

#### For DEBs
```
sudo sed -i -e '/experimental/ s/^#//g' /etc/apt/sources.list.d/libnvidia-container.list
sudo apt-get update
```
```
sudo apt-get install -y libnvidia-container-tools libnvidia-container1
```
#### For RPMs
```
sudo yum-config-manager --enable libnvidia-container-experimental
```
```
sudo yum install -y libnvidia-container-tools libnvidia-container1
```

**Comment by klueska** [comment]
`libnvidia-container-1.8.0-rc.2` is now live with some minor updates to fix some edge cases around `cgroupv2` support.
Assuming you followed the above, a simple `update` --> `install` should give you the latest.

**Note:** This does not directly add `ubuntu21.10` support, but you can point to the `ubuntu20.04` repo and install from there for now.

**Comment by klueska** [comment]
`libnvidia-container-1.8.0` with `cgroupv2` support is now GA

Release notes here:
https://github.com/NVIDIA/libnvidia-container/releases/tag/v1.8.0
