### ISSUE TITLE
Failed to do Docker Engine Setup

### ISSUE THREAD

**Issue by quintasxcv** [NVIDIA/nvidia-container-runtime#16]
Hello I am working on a Ubuntu 16.04 with Docker 17.12.1-1. I had already installed nvidia-docker2 before following your post.

I run Usage example without problems. I did the edition of conf file for Docker Engine Setup and after doing docker restart I got the following error:

Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.

This is the output of systemctl status docker.service:

● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─override.conf
   Active: inactive (dead) (Result: exit-code) since Mon 2018-03-05 17:55:44 CET; 17s ago
     Docs: https://docs.docker.com
  Process: 25885 ExecStart=/usr/bin/dockerd --host=fd:// --add-runtime=nvidia=/usr/bin/nvidia-container-runtime (code=exited, status=1/FAILURE)
 Main PID: 25885 (code=exited, status=1/FAILURE)

Mar 05 17:55:44 svstation systemd[1]: Failed to start Docker Application Container Engine.
Mar 05 17:55:44 svstation systemd[1]: docker.service: Unit entered failed state.
Mar 05 17:55:44 svstation systemd[1]: docker.service: Failed with result 'exit-code'.
Mar 05 17:55:44 svstation systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Mar 05 17:55:44 svstation systemd[1]: Stopped Docker Application Container Engine.
Mar 05 17:55:44 svstation systemd[1]: docker.service: Start request repeated too quickly.
Mar 05 17:55:44 svstation systemd[1]: Failed to start Docker Application Container Engine.

And this one for journalctl -xe:

-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has failed.
-- 
-- The result is failed.
Mar 05 18:04:35 svstation systemd[1]: docker.service: Unit entered failed state.
Mar 05 18:04:35 svstation systemd[1]: docker.service: Failed with result 'exit-code'.
Mar 05 18:04:36 svstation systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Mar 05 18:04:36 svstation systemd[1]: Stopped Docker Application Container Engine.
-- Subject: Unit docker.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has finished shutting down.
Mar 05 18:04:36 svstation systemd[1]: Closed Docker Socket for the API.
-- Subject: Unit docker.socket has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.socket has finished shutting down.
Mar 05 18:04:36 svstation systemd[1]: Stopping Docker Socket for the API.
-- Subject: Unit docker.socket has begun shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.socket has begun shutting down.
Mar 05 18:04:36 svstation systemd[1]: Starting Docker Socket for the API.
-- Subject: Unit docker.socket has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.socket has begun starting up.
Mar 05 18:04:36 svstation systemd[1]: Listening on Docker Socket for the API.
-- Subject: Unit docker.socket has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.socket has finished starting up.
-- 
-- The start-up result is done.
Mar 05 18:04:36 svstation systemd[1]: docker.service: Start request repeated too quickly.
Mar 05 18:04:36 svstation systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has failed.
-- 
-- The result is failed.
Mar 05 18:04:36 svstation systemd[1]: docker.socket: Unit entered failed state.
Mar 05 18:05:04 svstation sudo[26035]:      mqg : TTY=pts/4 ; PWD=/ ; USER=root ; COMMAND=/bin/journalctl -xe
Mar 05 18:05:04 svstation sudo[26035]: pam_unix(sudo:session): session opened for user root by (uid=0)

Thanks in advance, best regards.

Marcos.

**Comment by flx42** [comment]
`dockerd` could fail to start because of this line:
```
--add-runtime=nvidia=/usr/bin/nvidia-container-runtime (code=exited, status=1/FAILURE)
```
For instance, if you uninstalled our packages afterwards, is that the case? Does `/usr/bin/nvidia-container-runtime` exists?

**Comment by quintasxcv** [comment]
I tried to install the package through sudo apt-get install and it said it already exists. Yes the file exists on that location

**Comment by flx42** [comment]
You can do `sudo /usr/bin/dockerd` in your shell to check what's the error you are seeing.
But it's probably unrelated to nvidia-docker

**Comment by flx42** [comment]
any upddate @quintasxcv ?
