### ISSUE TITLE
Nvidia docker gpg key host is not working. [Ubuntu 20.04.3 LTS]

### ISSUE THREAD

**Issue by htinaunglu** [NVIDIA/nvidia-container-runtime#164]
I am on Ubuntu 20.04.3 LTS and trying to install tensorflow on docker image, but the keyring part is not working, so i tried the command `curl -L https://nvidia.github.io/nvidia-container-runtime/gpgkey |   sudo apt-key add -` but it doesn't get connected. Is the host down?

**Comment by elezar** [comment]
@htinaunglu I have just checked the command again and it works. Could you confirm that you are able to reach https://nvidia.github.io/nvidia-container-runtime/

Alternatively, https://nvidia.github.io/nvidia-container-runtime/ can be replaced with https://nvidia.github.io/libnvidia-container/ as these serve the same public GPG keys.

**Comment by htinaunglu** [comment]
> @htinaunglu I have just checked the command again and it works. Could you confirm that you are able to reach https://nvidia.github.io/nvidia-container-runtime/
> 
> Alternatively, https://nvidia.github.io/nvidia-container-runtime/ can be replaced with https://nvidia.github.io/libnvidia-container/ as these serve the same public GPG keys.

yes it still doesn't work til now. So I use my windows machine and currently going on this. 
I will let you know when it is fit.
I put my screen cap with this reply.
![Screenshot from 2022-02-09 15-13-46](https://user-images.githubusercontent.com/23364398/153158346-f33f2c0b-c96e-4d08-afc5-4d1bc7ec782e.png)

**Comment by elezar** [comment]
@htinaunglu could you try the key at https://nvidia.github.io/libnvidia-container/gpgkey instead?

**Comment by htinaunglu** [comment]
> @htinaunglu could you try the key at https://nvidia.github.io/libnvidia-container/gpgkey instead?

Yes this is the same as still now.

**Comment by elezar** [comment]
Closing this as the key is used regularly with now additional issues. 

Please also note the updated [installation instructions](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#installing-the-nvidia-container-toolkit)
