### ISSUE TITLE
Add support for rocky linux

### ISSUE THREAD

**Issue by mliradelc** [NVIDIA/nvidia-container-runtime#175]
Rocky linux is not in the list of supported distros. I would like to have it because Rocky is the spiritual successor of centos 8

**Comment by qhaas** [comment]
Compatibility with upstream (RHEL) is [a goal of Rocky](https://rockylinux.org/), so wouldn't the packages meant for RHEL8 suffice for all so-called 'RHEL Clones'?

**Comment by elezar** [comment]
We currently use `centos8` packages for most "RHEL Clones" -- mostly becase we already have the infrastructure set up to build and distribute these. We are evaluating whether Rocky Linux should replace this going forward.

For the time being,  installing the `centos8` packages on Rocky Linux should work as expected. If this is not the case, please let us know.
