### ISSUE TITLE
"nvidia.github.io/nvidia-container-runtime/ubuntu22.04/nvidia-container-runtime.list" contains ubuntu18.04 branch list.

### ISSUE THREAD

**Issue by coolwindjo** [NVIDIA/nvidia-container-runtime#176]
Please refer to [https://nvidia.github.io/nvidia-container-runtime/ubuntu22.04/nvidia-container-runtime.list](https://nvidia.github.io/nvidia-container-runtime/ubuntu22.04/nvidia-container-runtime.list)

**Comment by elezar** [comment]
This is the expected behaviour. See the notes here: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#linux-distributions

**Comment by elezar** [comment]
Please note the updated installation instructions [here](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#installing-the-nvidia-container-toolkit).
