### ISSUE TITLE
Can i get the docker image: nvidia/base/centos:7

### ISSUE THREAD

**Issue by MiiW** [NVIDIA/nvidia-container-runtime#178]
I'm trying to fix default cap issue in the v3.0.0 version becuse of upgrading fail, so turn to re-build a v3.0.0 hook version. but the docker image nvidia/base/centos:7 is missing. 
So, where can i get the docker image: nvidia/base/centos:7 ?

**Comment by MiiW** [comment]
> That image may be deprecated. You could try and use the "standard" centos7 images.
> 
> As a matter of interest, why are you not able to use a later version?

OK, i'ill try the standard image or a later version. And the reason is...  our system is too old, but serving online, and we try to avoid introducing too many changes... Anyway, thanks for your advice.

**Comment by elezar** [comment]
I assume that you were able to address your issue here.

If not, please let us know by opening a new issue against https://github.com/NVIDIA/nvidia-container-toolkit
