### ISSUE TITLE
Manual Installation Instructions (Other Linux like CoreOS)

### ISSUE THREAD

**Issue by kshitizbakshi** [NVIDIA/nvidia-container-runtime#18]
Hi,

I want to install nvidia-docker2 in CoreOS, but there exists no package for it. I'm prepared to follow some manual installation/provisioning steps but unable to find a source to follow. Can someone please help?

From what I pieced together until now, nvidia-docker2 is simply packaging which installs the nvidia-container-runtime and adds a docker daemon drop-in instructing to add the nvidia runtime to the daemon. Dropping a daemon manually won't be a problem, but I cannot find an nvidia-container-runtime binary for CoreOS or instructions to build it. (hence I opened this ticket in this repo).

Can you please help with instructions to install in arbitrary Linux distributions? Is the above understanding correct?

**Comment by lukeyeager** [comment]
:+1: Is this documented anywhere? Should we just dig through the packages for other distros to find out how to do this?

@Lemmons

**Comment by flx42** [comment]
the simplest way is to install Red Hat's fork of Docker, then you can simply drop nvidia-container-runtime-hook (provided on the release page, and is a static binary). You will still need to install `nvidia-container-cli` though.
If you use upstream docker, you will need to compile `runc` with a matching commit and security features (apparmor/selinux), then add the new runtime.

**Comment by archenroot** [comment]
@kshitizbakshi @lukeyeager - do you have any result, i am interested in Gentoo packages...

**Comment by archenroot** [comment]
@flx42 - I finished basic ebuild for Gentoo system of libnvidia-container project:
https://github.com/NVIDIA/libnvidia-container/issues/42

What should I do to have full nvidia-runtime, I welcome even some hacker way just make it work at least and later we can create special hooks, etc. artifacts so we are aligned with your way...

Thx for any kind of help.

**Comment by archenroot** [comment]
@flx42 - I use upstream Docker with following USE flags (features) enabled on Gentoo:
```
* Found these USE flags for app-emulation/docker-18.09.0:
 U I
 + + apparmor       : Enable AppArmor support. 
 + + aufs           : Enables dependencies for the "aufs" graph driver, including necessary kernel flags. 
 + + btrfs          : Enables dependencies for the "btrfs" graph driver, including necessary kernel flags. 
 + + container-init : Makes the a staticly-linked init system tini available inside a container. 
 - - device-mapper  : Enables dependencies for the "devicemapper" graph driver, including necessary kernel flags. 
 - - hardened       : Activate default security enhancements for toolchain (gcc, glibc, binutils)
 + + overlay        : Enables dependencies for the "overlay" graph driver, including necessary kernel flags. 
 + + pkcs11         : Enables pkcs-11 support. 
 + + seccomp        : Enable seccomp (secure computing mode) to perform system call filtering at runtime to increase security of programs
```
I have enabled AppArmor, but not hardened profile. Do you think I need recompile with hardened or apparmor is enough?

Thank you.
