### ISSUE TITLE
How to install on CentOS 9?

### ISSUE THREAD

**Issue by pumpkin-nbc** [NVIDIA/nvidia-container-runtime#185]
There is currently no relevant repository available

**Comment by elezar** [comment]
Hi @pumpkin-nbc. We don't officially test Centos9, but the Centos8 packages can be installed on this platform since the limiting factor is the minimum glibc version.

**Comment by pumpkin-nbc** [comment]
![image](https://github.com/NVIDIA/nvidia-container-runtime/assets/58675642/cbad05fd-ec18-4364-a35e-26da0339f39c)
But after installation, the file cannot be found

**Comment by elezar** [comment]
Please install the `nvidia-container-toolkit` package. This installs the full NVIDIA Container Toolkit stack.

**Comment by pumpkin-nbc** [comment]
Thank you, it's ready to use now

**Comment by elezar** [comment]
Thanks for confirming. I am closing this issue.
