### ISSUE TITLE
hint

### ISSUE THREAD

**Issue by Emilio942** [NVIDIA/nvidia-container-runtime#188]
https://github.com/NVIDIA/nvidia-container-runtime/blob/6f328ae638853b5b295deabfa08becc74f7273ef/README.md?plain=1#L17

Downloading doesn't work
http://cdimage.ubuntu.com/ubuntu-base/releases/16.04/release/ubuntu-base-16.04-core-amd64.tar.gz

the download worked
https://cdimage.ubuntu.com/ubuntu-base/releases/16.04/release/ubuntu-base-16.04.6-base-amd64.tar.gz

**Comment by elezar** [comment]
@Emilio942 the README is most likely out of date. Do you mind opening an MR against https://gitlab.com/nvidia/container-toolkit/container-runtime with updated instructions. It would be good to move to a newer ubuntu version, for example.
