### ISSUE TITLE
Inquire about the progress of work on the Debian 12 release

### ISSUE THREAD

**Issue by Lingzilla** [NVIDIA/nvidia-container-runtime#191]
Hi, I want to use nvidia-container-runtime on Debian 12, how long do I have to wait?

**Comment by elezar** [comment]
We are reworking our repositories to make this simpler, but for the moment please use the `debian11` packages.

```
distribution=debian11 \
      && curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
      && curl -s -L https://nvidia.github.io/libnvidia-container/$distribution/libnvidia-container.list | \
            sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
            sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
```

**Comment by elezar** [comment]
We have made general .deb packages available. The repositories for these can be configured as per our [documentation](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#installing-with-apt).

If there are problems following this approach, please open an issue against https://github.com/NVIDIA/nvidia-container-toolkit
