### ISSUE TITLE
Add Ubuntu 18.04 target

### ISSUE THREAD

**Issue by gijzelaerr** [NVIDIA/nvidia-container-runtime#22]

**Comment by flx42** [comment]
I was planning to do it around the actual release date of 18.04: https://wiki.ubuntu.com/BionicBeaver/ReleaseSchedule

**Comment by flx42** [comment]
By the way, on 18.04 you will need this patch for libnvidia-container: https://github.com/NVIDIA/libnvidia-container/commit/cef6c8f1ede04d65e753c288eec19d4af9b1f16c

**Comment by gijzelaerr** [comment]
We are already preparing our software for 18.04 and it seems quite stable, having access nvidia docker support would be very useful.

that said, with the runc fix i can now build my own  :) thanks.

**Comment by flx42** [comment]
I have 18.04 on my machine, and I'm using the 16.04 repo for now. It works fine, but I had to recompile libnvidia-container with the patch above.

**Comment by flx42** [comment]
Done in c9dbb7b
