### ISSUE TITLE
runtime hook using newer cli

### ISSUE THREAD

**Issue by clnperez** [NVIDIA/nvidia-container-runtime#26]
Using a kubernetes example:

`$ docker build -f nvidia-cuda-vector_Dockerfile -t cuda-vector-add:v0.1 .`

```
Sending build context to Docker daemon  2.046GB
Step 1/5 : FROM nvidia/cuda-ppc64le:8.0-devel-ubuntu16.04
 ---> 62553fb74993
Step 2/5 : RUN apt-get update && apt-get install -y --no-install-recommends         cuda-samples-$CUDA_PKG_VERSION &&     rm -rf /var/lib/apt/lists/*
 ---> Running in 1f1ddbb19617
OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/local/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --compat32 --graphics --utility --video --display --require=cuda>=8.0 --pid=121739 /var/lib/docker/aufs/mnt/8e537edc1ae0f2e5d7190854e90d35eee0d6d5251eb79d21a396811011333e05]\\\\nnvidia-container-cli configure: unrecognized option '--display'\\\\nTry `nvidia-container-cli configure --help' or `nvidia-container-cli configure\\\\n--usage' for more information.\\\\n\\\"\"": unknown
```

But if I bump up my `FROM` from 8.0 to 9.2, I don't get that error and my container builds. I see that the `--display` option was added to the `configure` subcommand in late Feb, so I'm thinking this is just a mismatch that expects the cli version to be newer? 

I found someone else running 8.0 on x86 has hit the same issue: https://stackoverflow.com/questions/49938024/errors-on-install-driverless-ai

```
$ nvidia-container-cli --version
version: 1.0.0
build date: 2018-02-07T18:40+00:00
build revision: c4cef33eca7ec335007b4f00d95c76a92676b993
build compiler: gcc-5 5.4.0 20160609
build platform: ppc64le
```

I'm being a little lazy and not figuring this out myself, but I'm sure you know pretty quickly what caused this so I don't feel too guilty about my laziness. :D

**Comment by flx42** [comment]
There are two problems here:
1. We broke the API for `--display`, sorry about that. It was still `alpha` stage at the time :)
You need a newer CLI.

2. We didn't upgrade this CUDA ppc64le image to add the new environment variables like:
```
                "NVIDIA_DRIVER_CAPABILITIES=compute,utility",
                "NVIDIA_REQUIRE_CUDA=cuda>=8.0",
```
Since those settings are not found, it will default to all the capabilities. With the above environment variable you won't get this issue.

So, I will fix 2.

**Comment by clnperez** [comment]
@flx42 Are you saying that I should be able to upgrade my package and get the newer cli from the repo?

**Comment by flx42** [comment]
@clnperez yes, is that not the case?

**Comment by flx42** [comment]
What's `dpkg -l '*nvidia*'`?

**Comment by clnperez** [comment]
https://gist.github.com/clnperez/a40bf9db71b4cf88b022e178defcfb9f

**Comment by flx42** [comment]
And what's `apt-cache policy libnvidia-container1`?

**Comment by clnperez** [comment]
```

**Comment by flx42** [comment]
Yes, you have an upgrade pending :)

**Comment by clnperez** [comment]
:D Ok, so, I could see that, and I have no idea how that dependency got mixed up. I suppose there was something on the system before from a previous experiment not done by me. I double-checked that all the dependencies look right and they do so, sorry and thanks for sticking with me!
