### ISSUE TITLE
Make selinux labes persist through reboots

### ISSUE THREAD

**Issue by garyedwards** [NVIDIA/nvidia-container-runtime#28]
Hi, I am using the nvidia-container-runtime-hook with fedora docker and based on advice in other issues, run the following command to set selinux labels to allow containers access to the nvidia devices:

    chcon -t container_file_t /dev/nvidia*

However on reboot these labels obviously get lost and need to be reset each time.  Is there a recommend way of making them persist, for example using udev or an nvidia specific way?

**Comment by garyedwards** [comment]
OK so I have settled for leaving the labels as they are and creating an selinux module to allow access to the devices from containers:

    (allow container_t xserver_misc_device_t (chr_file (read write open ioctl map)))

On my system only the /dev/nvidia* have the xserver_misc_device_t label so am reasonably happy with this.  Any other thoughts / concerns welcome.

**Comment by 3XX0** [comment]
Yes it's pretty much what you need to do.
You can get all the labels the driver uses with `semanage fcontext -l  | grep nvidia`

Other alternatives include:
- Creating a new type for GPU containers and apply it with `--security-opt label:...`
- Changing the label of every files and do something like `nvidia-container-cli -k list | restorecon -v -f -`
- Somehow leverage the [docker policy](https://www.unix.com/man-page/centos/8/docker_selinux/) or [x11 policy](https://linux.die.net/man/8/xserver_selinux).
