### ISSUE TITLE
Fix compilation from source

### ISSUE THREAD

**Issue by hdiethelm** [NVIDIA/nvidia-container-runtime#29]
It seams that access is denied:
nvidia-container-runtime/runtime$ make ubuntu18.04
make: *** Keine Regel, um „18.05.0-ubuntu18.04-runc“ zu erstellen.  Schluss.
runc="" && \
docker build --build-arg VERSION_ID="18.04" \
                        --build-arg RUNC_COMMIT="${runc}" \
                        --build-arg PKG_VERS="2.0.0+docker18.05.0" \
                        --build-arg PKG_REV="1" \
                        -t "nvidia/runtime/ubuntu:18.04-docker18.05.0" -f Dockerfile.ubuntu .
Sending build context to Docker daemon  67.07kB
Step 1/21 : ARG VERSION_ID
Step 2/21 : FROM nvidia/base/ubuntu:${VERSION_ID}
pull access denied for nvidia/base/ubuntu, repository does not exist or may require 'docker login'
Makefile:59: recipe for target '18.05.0-ubuntu18.04' failed
make: *** [18.05.0-ubuntu18.04] Error 1

nvidia-container-runtime/runtime$ docker pull nvidia/base/ubuntu
Using default tag: latest
Error response from daemon: pull access denied for nvidia/base/ubuntu, repository does not exist or may require 'docker login'

**Comment by flx42** [comment]
You have to do `make -C base ubuntu18.04` or `make -C ../base ubuntu18.04` (depending on where you are at) first.

**Comment by hdiethelm** [comment]
Thanks! Adding compilation instruction to the readme would help...
I tried to compile from source because for the actual docker, there is not yet a compatible version of nvidia-docker for Ubuntu 18.04.

make -C base ubuntu18.04
works but doesn't produce any packages (it shouldn't)

make ubuntu18.04
fails now with:
error: git apply: failed to read: Is a directory
The command '/bin/sh -c git checkout $RUNC_COMMIT &&     git apply /tmp/patches/runc/* &&     if [ -f vendor.conf ]; then vndr; fi &&     make BUILDTAGS="seccomp apparmor selinux" &&     mv runc $DIST_DIR/nvidia-container-runtime' returned a non-zero code: 128

With the following change, it works:
diff --git a/runtime/Dockerfile.ubuntu b/runtime/Dockerfile.ubuntu
index bd6744f..0d23eb2 100644
--- a/runtime/Dockerfile.ubuntu
+++ b/runtime/Dockerfile.ubuntu
@@ -39,7 +39,6 @@ ARG RUNC_COMMIT
 COPY runc/$RUNC_COMMIT/ /tmp/patches/runc
 
 RUN git checkout $RUNC_COMMIT && \
-    git apply /tmp/patches/runc/* && \
     if [ -f vendor.conf ]; then vndr; fi && \
     make BUILDTAGS="seccomp apparmor selinux" && \
     mv runc $DIST_DIR/nvidia-container-runtime

**Comment by flx42** [comment]
> there is not yet a compatible version of nvidia-docker for Ubuntu 18.04.

That's because there is not yet a compatible version of Docker CE for Ubuntu 18.04 :)
Use `docker.io` instead and it will work, we provide a package for that.
