### ISSUE TITLE
/usr/bin overlay uses `nosuid` argument preventing sudo

### ISSUE THREAD

**Issue by defunctzombie** [NVIDIA/nvidia-container-runtime#3]
Not sure if this repo is the appropriate place to post this issue. When I run the following command:

```
docker run --rm -it --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=all --rm ubuntu:14.04 cat /etc/mtab | grep usr/bin
```

The output shows:

```
overlay /usr/bin overlay rw,nosuid,nodev,relatime,lowerdir=/var/lib/docker/o...
```

Indicating that `/usr/bin` has been mounted with the nosuid option. When running in the container as a root user this does not present any issues. However, when running as a regular user and trying to invoke `sudo` at `/usr/bin/sudo` it results in the following error:

```
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
```

The expected behavior is for the sudo command to work.

I am not sure which line is responsible for mounting `/usr/bin` but presumably it has to do with making commands such as `nvidia-smi` available within the container. This is useful but certainly not at the expense of sudo capability. If this is outside the scope of this project to fix, then at least having a way to disable `/usr/bin` mounting would be appreciated to avoid any nosuid mount flags being set.

**Comment by flx42** [comment]
@3XX0 this was fixed by https://github.com/NVIDIA/libnvidia-container/commit/dabef1cd71fdea0ccd85f433534c08ec4862e56f, right? In this case, the fix will be picked up in the next release of libnvidia-container (tomorrow?).

**Comment by defunctzombie** [comment]
@flx42 I am not sure the above change is enough, if I am reading it correctly and the code that follows on this line https://github.com/NVIDIA/libnvidia-container/blob/7c943b1f0c094d01552115dd43921879cf13b7c8/src/nvc_mount.c#L61 then /usr/bin wound still be mounted with the suid bit unless the logic flow from https://github.com/NVIDIA/libnvidia-container/blob/master/src/nvc_mount.c#L324 is somehow going to cause the referenced for loop in mount_files to not iterate over the basenames of `/usr/bin` ?

**Comment by defunctzombie** [comment]
@flx42 in either case, I am comfortable building my own debs and will package up master libnvidia-container and give it a try.

**Comment by defunctzombie** [comment]
I build master of libnvidia-container and can confirm that it fixes my issue with sudo. Thank you and I look forward to the release 👏

**Comment by 3XX0** [comment]
Yeah sorry, will push new packages tomorrow

**Comment by 3XX0** [comment]
@defunctzombie FYI I pushed the new packages
