### ISSUE TITLE
Support running at node without GPU devices

### ISSUE THREAD

**Issue by l1b0k** [NVIDIA/nvidia-container-runtime#33]
Hi, I'm using k8s 1.11 and device-plugin .Some of my nodes has no GPU resource, device-plugin pod will crash .
Logs like below

```sh
container_linux.go:262: starting container process caused "process_linux.go:345: container init caused \"process_linux.go:328: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command:
[/usr/bin/nvidia-container-cli --load-kmods --debug=/dev/stderr configure --ldconfig=@/sbin/ldconfig --device=all --utility --pid=6666
```

There is a sloution to use Affinity in k8s,but i have to determine which node have GPU resource.
Another way is add some logical to check whether this node have GPU ,and return success when no GPU found .

 
https://github.com/NVIDIA/nvidia-container-runtime/blob/aa11413c18dbd08fb6fa4c617fc92c31d5cc2e79/hook/nvidia-container-runtime-hook/main.go#L89-L95

For now I made my change at line 94 ,and it works fine.

**Comment by flx42** [comment]
Please post your issue at https://github.com/NVIDIA/k8s-device-plugin
The best way is probably to modify the pod spec to have a `nodeSelector` in the device plugin DaemonSet.
