### ISSUE TITLE
Failed to install deb pkg

### ISSUE THREAD

**Issue by m3ngyang** [NVIDIA/nvidia-container-runtime#34]
I came across the following problem when installing pkg
```
# dpkg -i nvidia-container-runtime_2.0.0+docker1.12.6-1_amd64.deb
dpkg-deb: error: 'nvidia-container-runtime_2.0.0+docker1.12.6-1_amd64.deb' is not a debian format archive
dpkg: error processing archive nvidia-container-runtime_2.0.0+docker1.12.6-1_amd64.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 nvidia-container-runtime_2.0.0+docker1.12.6-1_amd64.deb
```
and my os is 
```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```

How to solve it ?

**Comment by flx42** [comment]
How did you download this deb package? Can you do `file nvidia-container-runtime_2.0.0+docker1.12.6-1_amd64.deb`?

**Comment by m3ngyang** [comment]
```
# file nvidia-container-runtime_2.0.0+docker1.12.6-1_amd64.deb
nvidia-container-runtime_2.0.0+docker1.12.6-1_amd64.deb: HTML document, UTF-8 Unicode text, with very long lines
```
and the pkg file was download from https://github.com/NVIDIA/nvidia-container-runtime/tree/gh-pages/ubuntu16.04/amd64

**Comment by flx42** [comment]
We have package repositories for each project, each one is documented, for instance:
https://nvidia.github.io/libnvidia-container/

If you can't use our package repositories, you can still mirror them with a tool or [manually](https://github.com/NVIDIA/nvidia-docker/issues/635#issuecomment-365160098)

**Comment by m3ngyang** [comment]
It works in the manual way, thx a lot!
