### ISSUE TITLE
can't start docker due to nvidia-container-runtime

### ISSUE THREAD

**Issue by bhomass** [NVIDIA/nvidia-container-runtime#35]
I am having no luck getting docker-ce to run on my ubunut. Everytime I try starting docker daemon, it fails and print out this command it is executing

Process: 16402 ExecStart=/usr/bin/dockerd --host=fd:// --add-runtime=nvidia=/usr/bin/nvidia-container-runtime (code=exite
 Main PID: 14715 (code=exited, status=1/FAILURE)

There is something wrong with is picture. First of all, I removed all nvidia docker related packages, and /usr/bin/nvidia-container-runtime doesn't even exists. Why is dockerd trying to add this as a runtime? 

I am guessing this is the problem right now. What do I do? do I find some configuration file and remove this --add-runtime parameter? Why is docker automatically adding it?

**Comment by flx42** [comment]
Did you follow these instructions?
https://github.com/NVIDIA/nvidia-container-runtime#docker-engine-setup

**Comment by bhomass** [comment]
ah, found it, and removed it. Now its running. hew, what a relief.
