### ISSUE TITLE
Setup local mirror for CentOS/RHEL

### ISSUE THREAD

**Issue by ddeimeke** [NVIDIA/nvidia-container-runtime#36]
Hi!

In our company only a few machines have direct access to the internet.

This is the reason why I need to setup a local mirror of CentOS/RHEL packages.

Can you please give me a starting URL for `wget --mirror`?

Thanks a lot

Dirk

**Comment by flx42** [comment]
Let's continue the discussion on `nvidia-docker`: https://github.com/NVIDIA/nvidia-docker/issues/805
