### ISSUE TITLE
Failed to start docker after installing docker container.

### ISSUE THREAD

**Issue by yuanzhedong** [NVIDIA/nvidia-container-runtime#38]
I got the same error message same with this [post](https://github.com/NVIDIA/nvidia-docker/issues/761) and Follow @flx42 solution I removed `--add-runtime=...` part and now docker runs again. the `--add-runtime=..` part is from the README [here](https://github.com/NVIDIA/nvidia-container-runtime#systemd-drop-in-file)
So could you please update the README?

**Comment by flx42** [comment]
Done.
