### ISSUE TITLE
RPM repository is unavailable

### ISSUE THREAD

**Issue by frankthetank** [NVIDIA/nvidia-container-runtime#4]
The RPM repository identified at [NVIDIA-docker](http://nvidia.github.io/nvidia-docker/) (CentOS 7 configuration) points to [NVIDIA Container Runtime](https://nvidia.github.io/nvidia-container-runtime/centos7/x86_64).  Unfortunately, no repository data comes back when I add that to my YUM configuration.

If I try to curl the URL I would normally expect to see repository contents but instead I get a 301 (Moved Permanently) showing a Location header that points to the same path with the HTTP protocol.  Querying for the HTTP (not HTTPS) path shows a 301 redirect back to the HTTPS path.

How or from where should I get the nvidia-container-runtime RPMs?

**HTTPS query**
```bash
curl -i https://nvidia.github.io/nvidia-container-runtime/centos7/x86_64
HTTP/1.0 200 Connection established

HTTP/1.1 301 Moved Permanently
Server: GitHub.com
Content-Type: text/html
Location: http://nvidia.github.io/nvidia-container-runtime/centos7/x86_64/
Access-Control-Allow-Origin: *
Expires: Tue, 31 Oct 2017 13:58:48 GMT
Cache-Control: max-age=600
X-GitHub-Request-Id: E052:327E:D6217C2:1356DBD7:59F87F3F
Content-Length: 178
Accept-Ranges: bytes
Date: Tue, 31 Oct 2017 13:48:48 GMT
Via: 1.1 varnish
Age: 0
Connection: keep-alive
X-Served-By: cache-iad2123-IAD
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1509457728.107603,VS0,VE6
Vary: Accept-Encoding
X-Fastly-Request-ID: b07db5257415504b3d8ff5838ab4a6e01e21b2fc

<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
**HTTP query**
```bash
curl -i http://nvidia.github.io/nvidia-container-runtime/centos7/x86_64
HTTP/1.1 301 Moved Permanently
Server: GitHub.com
Content-Type: text/html
Location: https://nvidia.github.io/nvidia-container-runtime/centos7/x86_64
X-GitHub-Request-Id: 1F1A:7A69:12EDC0A8:1B64C01A:59F87C91
Content-Length: 178
Accept-Ranges: bytes
Date: Tue, 31 Oct 2017 13:51:55 GMT
Via: 1.1 varnish
Age: 872
X-Served-By: cache-iad2643-IAD
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1509457916.920828,VS0,VE0
Vary: Accept-Encoding
X-Fastly-Request-ID: 65c6947865bb90f76f9d0ffb85d1e1e06f62c8f9
Proxy-Connection: Keep-Alive

<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by flx42** [comment]
> Unfortunately, no repository data comes back when I add that to my YUM configuration.

What do you mean here? What did you do and what do you see?

> If I try to curl the URL I would normally expect to see repository contents but instead I get a 301 (Moved Permanently) showing a Location header that points to the same path with the HTTP protocol.

No, it's not the same Location.
But why are you trying to curl this repository anyway? You can't expect repositories to be auto-indexed (i.e. have an HTML directory listing).

The following works, and that's sufficient:
```
$ curl https://nvidia.github.io/nvidia-container-runtime/centos7/x86_64/repodata/repomd.xml
$ curl -O https://nvidia.github.io/nvidia-container-runtime/centos7/x86_64/nvidia-container-runtime-1.0.0-1.docker17.09.0.x86_64.rpm
```

If you want to browse the files: https://github.com/NVIDIA/nvidia-container-runtime/tree/gh-pages

**Comment by frankthetank** [comment]
OK - so repository browsing is not enabled.  That's not a problem.  I was only trying to browse to manually see that content existed (lazy, yes).  

After some more troubleshooting I think I have found where the issue is and why it was displaying the way it did.

Nutshell: I am using Artifactory to proxy YUM repositories into my lab.  I've got the three NVIDIA repositories listed above added individually and then aggregated into a virtual repository.  The issue is that the .xz files available from the libcontainer project (NVIDIA/libnvidia-container#5) are corrupt or invalid.  When this happens during Artifactory's aggregation work it is failing the entire return and telling me that the objects cannot be found.

I can reproduce this by directly downloading a file and trying to extract it:
```
curl -O https://nvidia.github.io/libnvidia-container/centos7/x86_64/repodata/e71656904242b818e3e0083f0bc838d1a542180a6698ed6a06525250ccb084c791bb65ba798a824e7da549507ecf6e53f3c3d8c6a440e9bf8a4b3513fdd2fb41-filelists.xml.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9340  100  9340    0     0  30983      0 --:--:-- --:--:-- --:--:-- 31029

xz --decompress e71656904242b818e3e0083f0bc838d1a542180a6698ed6a06525250ccb084c791bb65ba798a824e7da549507ecf6e53f3c3d8c6a440e9bf8a4b3513fdd2fb41-filelists.xml.xz 
xz: e71656904242b818e3e0083f0bc838d1a542180a6698ed6a06525250ccb084c791bb65ba798a824e7da549507ecf6e53f3c3d8c6a440e9bf8a4b3513fdd2fb41-filelists.xml.xz: File format not recognized
```

This does not appear to be an issue with _this_ project.  I will update the other issue with the above notes.  Sorry for the noise.
