### ISSUE TITLE
No hook config file for ppc64le

### ISSUE THREAD

**Issue by dllehr81** [NVIDIA/nvidia-container-runtime#40]
@flx42  We noticed you removed the steps to manually create the hook config file from your nvidia-docker README(https://github.com/NVIDIA/nvidia-docker/commit/ddb80bf8f1f844f82afa6b93488e830de26e5977)

However, we also see that the nvidia-container-runtime update that moves the hook config file into the `nvidia-container-runtime-hook` package(https://github.com/NVIDIA/nvidia-container-runtime/commit/7372924195fb6451b7d1909ee679c0daf68a4e8c)  hasn't been rebuilt for `ppc64le`.  

So at this point we're in limbo, there are no steps to create the file, but the package doesn't include them either.  Is it possible to rebuild the ppc64le version of `nvidia-container-runtime-hook`?

**Comment by flx42** [comment]
Yes, I plan to rebuild the ppc64le packages this week, if everything goes
as expected.

Sorry about the passage to limbo.

**Comment by dllehr81** [comment]
Don't even sweat it!  I've had the canned instructions for so long, I didn't even notice they disappeared upstream.

**Comment by flx42** [comment]
Done with https://github.com/NVIDIA/nvidia-container-runtime/commit/570416f5e9cbefea49c9bbb3eb32ea0dbd3605ee
