### ISSUE TITLE
Need Nvidia docker 2 for 18.09.1 

### ISSUE THREAD

**Issue by cheyang** [NVIDIA/nvidia-container-runtime#46]
Docker CE 18.09.1 has released,  please support it in Nvidia-container-runtime. Thanks.

**Comment by RenaudWasTaken** [comment]
Hello!

We are aware of this. This won't happen before Monday.

**Comment by cheyang** [comment]
Thank you for this effort! Not urgent

**Comment by cheyang** [comment]
@RenaudWasTaken , may I know what's the plan for it? Thanks for your response.

**Comment by RenaudWasTaken** [comment]
Hello @cheyang!

We'll be taking care of this today.

**Comment by RenaudWasTaken** [comment]
Closing as packages were released.

**Comment by cheyang** [comment]
Thanks.
