### ISSUE TITLE
ppc64le, RedHat7.6 docker-nvidia2 

### ISSUE THREAD

**Issue by stephanakeborg** [NVIDIA/nvidia-container-runtime#48]
Hi
I´m trying to find the nvidia2-docker for ppc64le RedHat (power9 repo), any tips would be perfect.
Cheers
S

**Comment by Eloring** [comment]
try this Using nvidia-docker 2.0 with RHEL 7 issued in IBM-developer:
https://developer.ibm.com/linuxonpower/2018/09/19/using-nvidia-docker-2-0-rhel-7/#install-docker

**Comment by RenaudWasTaken** [comment]
Closing in favor of: https://github.com/NVIDIA/nvidia-docker/issues/1186
