### ISSUE TITLE
Usage example fail

### ISSUE THREAD

**Issue by hcv1027** [NVIDIA/nvidia-container-runtime#51]
Hi, I run the README usage example, and it is failed.
The usage example:
> cd $(mktemp -d) && mkdir rootfs
curl -sS http://cdimage.ubuntu.com/ubuntu-base/releases/16.04/release/ubuntu-base-16.04-core-amd64.tar.gz | tar --exclude 'dev/*' -C rootfs -xz
nvidia-container-runtime spec
sed -i 's;"sh";"nvidia-smi";' config.json
sed -i 's;\("TERM=xterm"\);\1, "NVIDIA_VISIBLE_DEVICES=0";' config.json
sudo nvidia-container-runtime run nvidia_smi

The error log:
> container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:407: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig --device=0 --utility --pid=11009 /tmp/tmp.1fN7JGkKQQ/rootfs]\\\\nnvidia-container-cli: ldcache error: process /sbin/ldconfig failed with error code: 127\\\\n\\\"\""

This error log is very similar to the one I got as I run the nvidia-docker2 test command `docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi`, so I guess my problem comes from `nvidia-container-runtime`
> docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:407: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig --device=all --compute --utility --require=cuda>=10.1 brand=tesla,driver>=384,driver<385 brand=tesla,driver>=410,driver<411 --pid=10900 /var/lib/docker/aufs/mnt/51dfbfd55f1095ff103cf334aca6459cf1e10a4152494b7e991939fe63b463e2]\\\\nnvidia-container-cli: ldcache error: process /sbin/ldconfig failed with error code: 127\\\\n\\\"\"": unknown.

How can I fix it?

I provide my system information below:
Kernel version from `uname -a`:
> Linux josper-ThinkPad-T460p 4.15.0-47-generic #50~16.04.1-Ubuntu SMP Fri Mar 15 16:06:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Driver information from `nvidia-smi -a`:

> ==============NVSMI LOG==============
> 
> Timestamp                           : Thu Apr 18 11:13:20 2019
> Driver Version                      : 418.40.04
> CUDA Version                        : 10.1
> 
> Attached GPUs                       : 1
> GPU 00000000:02:00.0
>     Product Name                    : GeForce 940MX
>     Product Brand                   : GeForce

Docker version from `docker version`:

> Client:
>  Version:           18.09.5
>  API version:       1.39
>  Go version:        go1.10.8
>  Git commit:        e8ff056
>  Built:             Thu Apr 11 04:44:24 2019
>  OS/Arch:           linux/amd64
>  Experimental:      false
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          18.09.5
>   API version:      1.39 (minimum version 1.12)
>   Go version:       go1.10.8
>   Git commit:       e8ff056
>   Built:            Thu Apr 11 04:10:53 2019
>   OS/Arch:          linux/amd64
>   Experimental:     false

Nvidia packages version from `dpkg -l '*nvidia*'`:
![nvidia-package](https://user-images.githubusercontent.com/12728923/56336055-7295f480-61d1-11e9-99f8-69c4d0fe8b81.png)

NVIDIA container library version from `nvidia-container-cli -V`:
![nvidia-container-cli](https://user-images.githubusercontent.com/12728923/56336098-a1ac6600-61d1-11e9-948a-3bf167b5b05f.png)

Nvidia-docker version from `nvidia-docker --version`:

> Docker version 18.09.5, build e8ff056

**Comment by RenaudWasTaken** [comment]
Hello!

Sorry for the lack of answer, this repo is usually not meant to have issues opened on. This was fixed in a previous release a long time ago :)
Feel free to reopen if you see that issue again.
