### ISSUE TITLE
Building for ubuntu 19.04 - can't find Docker image

### ISSUE THREAD

**Issue by russkel** [NVIDIA/nvidia-container-runtime#54]
I am trying to build the runtime for Ubuntu 19.04 by making some modifications to the Makefile and using the same patchset as 18.04. However I am stuck at the point where it is trying to grab a ```nvidia/base/ubuntu:19.04``` image and yields:

```
docker build --build-arg VERSION_ID="19.04" \
                        --build-arg RUNC_COMMIT="6635b4f0c6af3810594d2770f662f34ddc15b40d" \
                        --build-arg PKG_VERS="2.0.0+docker" \
                        --build-arg PKG_REV="1" \
                        -t "nvidia/runtime/ubuntu:"19.04"-docker" -f Dockerfile.ubuntu .
Sending build context to Docker daemon  69.12kB
Step 1/21 : ARG VERSION_ID
Step 2/21 : FROM nvidia/base/ubuntu:${VERSION_ID}
pull access denied for nvidia/base/ubuntu, repository does not exist or may require 'docker login'
make: *** [Makefile:81: ubuntu] Error 1
```

I guess this is to be expected, but I was unable to find the Dockerfiles for nvidia/base/ubuntu so that I could make one for ubuntu 19.04. Any tips would be appreciated, thanks.

**Comment by russkel** [comment]
Any chance of a hand with this @flx42 ?

**Comment by RenaudWasTaken** [comment]
https://github.com/NVIDIA/nvidia-docker/issues/971#issuecomment-489496761

**Comment by russkel** [comment]
Thanks @RenaudWasTaken !

**Comment by russkel** [comment]
@RenaudWasTaken is the image I mentioned above proprietary hence there being no Dockerfiles?

**Comment by RenaudWasTaken** [comment]
No it's because we don't build nvidia-docker for non LTS versions of ubuntu.
The base images are build in the base folder.

**Comment by russkel** [comment]
>  The base images are built in the base folder.

I am blind. Thank you.
