### ISSUE TITLE
Issue installing nvidia-container-runtime

### ISSUE THREAD

**Issue by hanklin3** [NVIDIA/nvidia-container-runtime#56]
$ sudo apt-get install nvidia-container-runtime
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package nvidia-container-runtime is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  nvidia-container-runtime-hook

E: Package 'nvidia-container-runtime' has no installation candidate

---------------

Ubuntu 14.04

**Comment by RenaudWasTaken** [comment]
Hello!

Please follow the nvidia-docker2 instructions: github.com/NVIDIA/nvidia-docker

Thanks!
