### ISSUE TITLE
ubuntu18.04/arm64 Release Not Found 

### ISSUE THREAD

**Issue by bogflap** [NVIDIA/nvidia-container-runtime#59]
Just to be clear here. The Transfer Learning Toolkit on the Jetson Nano requires the nvidia-docker and the nvidia-container-runtime 2.0 be installed. The Jetson Nano is an arm64 based architecture. So this means the Transfer Learning Toolkit cannot be installed or run on the Jetson Nano?

**Comment by RenaudWasTaken** [comment]
```
Just to be clear here. The Transfer Learning Toolkit on the Jetson Nano requires the nvidia-docker and the nvidia-container-runtime 2.0 be installed
```

They don't require nvidia-docker to be installed :)

**Comment by bogflap** [comment]
Can you give me a clue. Can you recommend a URL to help me out
