### ISSUE TITLE
Is this a replacement of nvidia-docker in the future?

### ISSUE THREAD

**Issue by ScorpioCPH** [NVIDIA/nvidia-container-runtime#6]
@flx42 Hi, I just found this project and have a try on my local, it is awesome!

I'm just wondering is this a replacement of `nvidia-docker` in the future?
We have used `nvidia-docker` `2.0` in staging env, and i see [nvidia-docker](https://github.com/NVIDIA/nvidia-docker) project is still on the way to 2.0 release.

What is this project goal? Will it replace `nvidia-docker`?

**Comment by flx42** [comment]
nvidia-docker 2.0 uses `nvidia-container-runtime` actually. That's what happens when you do `docker run --runtime=nvidia`.

**Comment by ScorpioCPH** [comment]
Gotcha! Thanks very much for your explanation! @flx42

**Comment by flx42** [comment]
Sure, you can also look at #1 and https://github.com/kubernetes-incubator/cri-o/issues/1222 to learn more.
