### ISSUE TITLE
Ubuntu18.04/amd64 Release Not Found

### ISSUE THREAD

**Issue by dcarastan** [NVIDIA/nvidia-container-runtime#60]
https://nvidia.github.io/libnvidia-container/ubuntu18.04/libnvidia-container.list is listing `deb https://nvidia.github.io/libnvidia-container/ubuntu18.04/$(ARCH) /`. This is all fine but https://nvidia.github.io/libnvidia-container/ubuntu18.04/amd64 reports `# Unsupported distribution! # Check https://nvidia.github.io/libnvidia-container` instead of a list of packages.

**Comment by RenaudWasTaken** [comment]
Hello!

We don't have an index file in the amd64 folder which is why your are getting the default 404 (see the gh-pages branch).

The Debian packages are however still available in that folder (check out the gh-pages branch).
