### ISSUE TITLE
ppc64le RHEL 7.6 meet this error "exec: \"nvidia-smi\": executable file not found in $PATH": unknown.

### ISSUE THREAD

**Issue by Eloring** [NVIDIA/nvidia-container-runtime#62]
### ENV
RHEL 7.6
ppc64le (IBM Power8)
Docker version: 18.03.1-ce
Driver version: 418.67 
CUDA Version: 10.1
CuDNN Version: 7.6
2GPU: Tesla K80
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.67             Driver Version: 418.67           CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000002:03:00.0 Off |                  Off |
| N/A   39C    P0    55W / 149W |      0MiB / 12206MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           Off  | 00000002:04:00.0 Off |                  Off |
| N/A   30C    P0    42W / 149W |      0MiB / 12206MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

---

I have read carefully the documentation and frequently asked questions, unfortunately, the error still exist.

### 1. Issue description

$ docker run --rm nvidia/cuda-ppc64le nvidia-smi
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"nvidia-smi\": executable file not found in $PATH": unknown.

### 2. Steps to reproduce the issue

I have follow this [RHEL 7.4/7.5 (docker)](https://github.com/NVIDIA/nvidia-docker#centos-7-docker-rhel-7475-docker) and the FAQ [docker-ce on ppc64le](https://github.com/nvidia/nvidia-docker/wiki/Frequently-Asked-Questions#do-you-support-powerpc64-ppc64le)

~~~
$ docker volume ls -q -f driver=nvidia-docker | xargs -r -I{} -n1 docker ps -q -a -f volume={} | xargs -r docker rm -f
$ yum remove nvidia-docker

$ distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
$ curl -s -L https://nvidia.github.io/nvidia-container-runtime/$distribution/nvidia-container-runtime.repo | \
  sudo tee /etc/yum.repos.d/nvidia-container-runtime.repo

$ yum install -y nvidia-container-runtime-hook

$ docker run --rm nvidia/cuda-ppc64le nvidia-smi
~~~

### BTW

I followed this [if you use docker-ce with CentOS/RHEL on ppc64le, you need to register the nvidia runtime manually](https://github.com/nvidia/nvidia-container-runtime#docker-engine-setup)

~~~
yum install nvidia-container-runtime
~~~
add this _--add-runtime=nvidia=/usr/bin/nvidia-container-runtime_ to _/docker.service.d/override.conf_

and I tried the other two registration methods separately

Unfortunately, none of them works.

### It would be very grateful if someone point me the solution.

**Comment by kiendang** [comment]
try `docker run --runtime=nvidia --rm nvidia/cuda-ppc64le nvidia-smi`

**Comment by Eloring** [comment]
@kiendang 
I have tried that before and it didn't work:
/usr/bin/docker-current: Error response from daemon: oci runtime error: flag provided but not defined: -console.

**Comment by whillas** [comment]
`sudo apt install nvidia-container-runtime` worked for me

**Comment by KansaiUser** [comment]
I have the same problem but when running 
`sudo apt install nvidia-container-runtime`
I got 

`E: Unable to locate package nvidia-container-runtime`

How can I solve this. Any help would be appreciated

**Comment by klueska** [comment]
All you should need to do is:
```
sudo apt install nvidia-container-toolkit
```
And none of that other stuff you did around it should be needed.

In fact, doing this:
yum install -y nvidia-container-runtime-hook

**Comment by klueska** [comment]
Regarding:
> E: Unable to locate package nvidia-container-runtime
> How can I solve this. Any help would be appreciated

That seems like you haven't configured your apt repos according to the following before attempting to install:
https://github.com/NVIDIA/nvidia-docker#ubuntu-160418042004-debian-jessiestretchbuster

That said, you should be installing either `nvidia-docker2` or `nvidia-container-toolkit` and not (`nvidia-container-runtime` directly, which gets pulled in as a dependency of `nvidia-docker2`).

**Comment by KansaiUser** [comment]
I did what is indicated here [https://nvidia.github.io/nvidia-container-runtime/](url) and now I got a different error

> docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused “process_linux.go:430: container init caused “process_linux.go:413: running prestart hook 1 caused \“error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request\\n\”””: unknown.
