### ISSUE TITLE
Can't find runc commit for copy during build  opensuse 15.1

### ISSUE THREAD

**Issue by MrYoloSwaggerMan** [NVIDIA/nvidia-container-runtime#67]
Hello,

the make process have a problem to COPY

Removing intermediate container b1450a3abaaf
 ---> 15f2934bdce9
Step 13/20 : ENV DIST_DIR=/tmp/nvidia-container-runtime-$PKG_VERS/SOURCES
 ---> Running in 71624c12f968
Removing intermediate container 71624c12f968
 ---> cd5f5f8d7569
Step 14/20 : RUN mkdir -p $DIST_DIR /dist
 ---> Running in a6194882f562
Removing intermediate container a6194882f562
 ---> f43d95ca9e82
Step 15/20 : ARG RUNC_COMMIT
 ---> Running in acdecb4e1d81
Removing intermediate container acdecb4e1d81
 ---> 156291f32578
Step 16/20 : COPY runc/$RUNC_COMMIT/ /tmp/patches/runc
COPY failed: no source files were specified
make[1]: *** [Makefile:188: 18.09.6-opensuse_leap15.1] Error 1
make[1]: Leaving directory '/test/nvidia-container-runtime-opensuse/runtime'
make: *** [Makefile:33: runtime-opensuse_leap15.1] Error 2
make: Leaving directory '/test/nvidia-container-runtime-opensuse'

**Comment by MrYoloSwaggerMan** [comment]
Should the echo $RUNC_COMMIT get some output?

Removing intermediate container 61bfdccb74a8
 ---> fc7a543120de
Step 4/20 : RUN go get github.com/LK4D4/vndr
 ---> Running in 644fbcbac851
Removing intermediate container 644fbcbac851
 ---> e5703f7bf215
Step 5/20 : WORKDIR $GOPATH/src/github.com/opencontainers/runc
 ---> Running in 81bfc2ff3293
Removing intermediate container 81bfc2ff3293
 ---> 83992b260e28
Step 6/20 : RUN ls -ltr
 ---> Running in 2a7334f76144
total 0
Removing intermediate container 2a7334f76144
 ---> b8676d9b4258
Step 7/20 : RUN git clone https://github.com/opencontainers/runc.git .
 ---> Running in 9bf2564de59b
Cloning into '.'...
Removing intermediate container 9bf2564de59b
 ---> a46770e5ed5f
Step 8/20 : RUN echo $RUNC_COMMIT
 ---> Running in 39aff91c366d

Removing intermediate container 39aff91c366d
 ---> b4deaecd8ca7
Step 9/20 : ARG PKG_VERS
 ---> Running in 44d7b75a739a
Removing intermediate container 44d7b75a739a
 ---> a256e62c6743
Step 10/20 : ARG PKG_REV
 ---> Running in 325177a44585
Removing intermediate container 325177a44585
 ---> 3b1c57c21f07
Step 11/20 : ENV VERSION $PKG_VERS
 ---> Running in ba7c3a0482a3

**Comment by Ethyling** [comment]
Should be fix with the new runtime
