### ISSUE TITLE
GPG check failing

### ISSUE THREAD

**Issue by graemedavidson** [NVIDIA/nvidia-container-runtime#70]
Running yum update shows

`[Errno -1] repomd.xml signature could not be verified for libnvidia-container`

Disabling repo_gpgpcheck resolves as temp fix

**Comment by qhaas** [comment]
I was able to use the centos7 repo with `repo_gpgpcheck` enabled this morning without issue, resolved?

**Comment by graemedavidson** [comment]
Thanks for update @qhaas now working indeed
