### ISSUE TITLE
Does nvidia-container-runtime provide cuda?

### ISSUE THREAD

**Issue by hubutui** [NVIDIA/nvidia-container-runtime#71]
Hey, I'm confused about what nvidia-container-runtime do. Here are my questions:
1. Am I right that nvidia-container-runtime provide nvidia driver from host to container? 
2. If cuda is also provided to the container from host, could I install via host system's apt or runfile?
3. If cuda is not provided to the container from host, then I should install one in the container, am I right?
4. What is `NVIDIA_REQUIRE_CUDA` used for?

**Comment by nvjmayo** [comment]
1. yes. it allows containers to "see" your GPU. 
2. CUDA may be ran inside a container. It is not part of the nvidia-container-runtime package. There are sample images with CUDA already installed if you want to try them: `docker run -it --rm --gpus all nvidia/cuda:10.0-base`
3. Yes, either install CUDA in your container or use a base image with CUDA already installed
4. NVIDIA_REQUIRE_* are optional values. This one is used to control the CUDA version that is visible from the container. example: `NVIDIA_REQUIRE_CUDA=cuda>=9.0`
See also: https://github.com/NVIDIA/nvidia-container-runtime#nvidia_require_cuda
