### ISSUE TITLE
nvidia.github.io is broken for ubuntu 18.04

### ISSUE THREAD

**Issue by tomponline** [NVIDIA/nvidia-container-runtime#76]
The page https://nvidia.github.io/nvidia-container-runtime/ instructs users to use `nvidia.github.io` as the source for the download repos. However http://nvidia.github.io/ is giving a 404.

**Comment by tomponline** [comment]
I am getting this error:

```
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://nvidia.github.io/libnvidia-container/ubuntu18.04/amd64  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6ED91CA3AC1160CD
```

**Comment by PeS-hkfree** [comment]
Same applies for CentOS 7 on PPC64LE too...

**Comment by Ternique** [comment]
solution can be found here:

https://github.com/NVIDIA/nvidia-docker/issues/1081

**Comment by tomponline** [comment]
Thanks @Ternique just doing 

```
curl -s -L https://nvidia.github.io/nvidia-container-runtime/gpgkey | \
  sudo apt-key add -
```

Fixed it for me.

**Comment by RenaudWasTaken** [comment]
Sorry for the late reply, nvidia-container-runtime is not a repository that we check regularly.
Please open your issues on the nvidia-docker repository.

nvidia.github.io is not index and is expected to give a 404.
You can check the page here: nvidia.github.io/nvidia-docker

```
curl -s -L https://nvidia.github.io/nvidia-container-runtime/gpgkey | \
  sudo apt-key add -
```

Will indeed fix it :)

**Comment by sirgogo** [comment]
```
$ curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
gpg: no valid OpenPGP data found.

```

**Comment by nvjmayo** [comment]
Please make sure that you are not being redirected to a different host. I cut and pasted yours exactly and it works.
```
 $ curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
OK
```

Check that https://nvidia.github.io/nvidia-docker/gpgkey indeed does download a PGP PUBLIC KEY BLOCK. The HTTP headers do show that the file was updated last week (Nov 13):
```
HTTP/2 200
server: GitHub.com
content-type: application/octet-stream
last-modified: Wed, 13 Nov 2019 00:59:22 GMT
etag: "5dcb556a-c5b"
access-control-allow-origin: *
expires: Fri, 15 Nov 2019 02:23:36 GMT
cache-control: max-age=600
x-proxy-cache: MISS
x-github-request-id: DE62:5805:25146:2A908:5DCE09D0
accept-ranges: bytes
date: Tue, 19 Nov 2019 23:05:50 GMT
via: 1.1 varnish
age: 302
x-served-by: cache-pao17443-PAO
x-cache: HIT
x-cache-hits: 1
x-timer: S1574204750.321693,VS0,VE1
vary: Accept-Encoding
x-fastly-request-id: d3f9cacec2f260fdf3351d1a9ed4a3d9161e60c1
content-length: 3163
```

I hope this additional information helps track down your problem.

**Comment by Shen-Kirren** [comment]
> Didn't work for me:
> 
> ```
> $ curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
> gpg: no valid OpenPGP data found.
> ```
> 
> Any ideas?

the same occuers, wait for a reply
