### ISSUE TITLE
rhel 7.7 unsupported distribution!

### ISSUE THREAD

**Issue by choppercop2003** [NVIDIA/nvidia-container-runtime#79]
I am running rhel7.7 and attempted the commands you have to get the correct nvidia-container-runtime and I get the below response. Is there another way to get the nvidia-container-runtime for rhel7.7? 

- distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
          resolved to "rhel7.7" as it should
- curl -s -L https://nvidia.github.io/nvidia-container-runtime/$distribution/nvidia-container-runtime.repo | sudo tee /etc/yum.repos.d/nvidia-container-runtime.repo

            # Unsupported distribution!
            # Check https://nvidia.github.io/nvidia-container-runtime

**Comment by SyBernot** [comment]
Same problem on CentOS 8

**Comment by RenaudWasTaken** [comment]
Hello there!
This was fixed a while back :)
