### ISSUE TITLE
error: unable to recognize: no matches for kind "DaemonSet" in version "extensions/v1beta1"

### ISSUE THREAD

**Issue by jobvarkey** [NVIDIA/nvidia-container-runtime#80]
Hi,

The following error comes up when creating the daemon set in kubernetes v1.16.0 .

root@0939-jdeml-m01:~# kubectl create -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/1.0.0-beta/nvidia-device-plugin.yml
error: unable to recognize "https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/1.0.0-beta/nvidia-device-plugin.yml": no matches for kind "DaemonSet" in version "extensions/v1beta1"

Please advise how to get this fixed.

Thanks.

**Comment by RenaudWasTaken** [comment]
Fixed in the latest release.
This is the wrong repository.

**Comment by jobvarkey** [comment]
Thank You
