### ISSUE TITLE
nvidia-container-cli: initialization error: cuda error: unknown error\\\\n\\\"\"": unknown.

### ISSUE THREAD

**Issue by JerrettLevensalor** [NVIDIA/nvidia-container-runtime#81]
nvidia-container-cli Version 1.05 does not work with amazon linux 2 but version 1.0.0 does work on amazon linux 2 that is available on the Nvidia marketplace AMI for Tesla GPU.  Any idea on why does 1.05 not work?  Since amazon has Docker AWS 18.06 there is no choice but to use nvidia-docker2 for now.  So does your marketplace AMI not consume your own repo builds?  Followed the github references but to be fair they are all over the place.  Cuda is not needed but in order to test a simple nvidia-smi in a container 
Driver TESLA K80 tests on both p2.xlarge for marketplace and default amazon linux 2.  
NVIDIA rpm drivers tested locally were 410.104 and 418.87.00 on amazon linux 2 but they both failed with the same errors.  

Description: 
Using an amazon linux ami from the marketplace provided by Nvidia works but is using outdated libraries then what is building from the NVIDIA repos directly as of October 2019.  The updated repos are not working trying to run a test nvidia-smi inside a container using the newer code updates.  

Error: 
$sudo docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: cuda error: unknown error\\\\n\\\"\"": unknown.

*********************
NOT WORKING 

Reproduce not working: amazon linux 2 (non-marketplace) 
Verify os version: cat /etc/os-release 
OS version:
cat /etc/os-release 
NAME="Amazon Linux"
VERSION="2"
ID="amzn"

With uname -a: 
4.14.146-119.123.amzn2.x86_64

Docker version: 18.06.1-ce 
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a215d7133c34aa18e3b72b4a21fd0c6136
 Built:             Mon Jul  1 18:51:44 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a/18.06.1-ce
  Built:            Mon Jul  1 18:53:20 2019
  OS/Arch:          linux/amd64
  Experimental:     false

Download and install NVIDIA drivers 
Manually install with ./NVIDIA-Linux-x86_64-418.87.00.run --disable-nouveau  --install-libglvnd --silent 

Install nvidia-docker2:   
yum install nvidia-docker2

Get installed versions with rpm -qa '*nvidia*'
libnvidia-container-tools-1.0.5-1.x86_64
libnvidia-container1-1.0.5-1.x86_64
nvidia-container-toolkit-1.0.5-2.amzn2.x86_64
nvidia-docker2-2.2.2-1.noarch
nvidia-container-runtime-3.1.4-1.x86_64

Get the container cli version with nvidia-container-cli -V
version: 1.0.5

Validate NVIDIA drivers work on the host: 
$ nvidia-smi
Wed Oct  2 20:32:42 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.87.00    Driver Version: 418.87.00    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 00000000:00:1E.0 Off |                    0 |
| N/A   61C    P8    32W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
========|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

Fails to run a test nvidia-smi 
$sudo docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: cuda error: unknown error\\\\n\\\"\"": unknown.

***********************************
WORKING:  Amazon marketplace AMI
Amazon Linux 2 AMI with NVIDIA TESLA GPU

ec2-user@xx]$ cat /etc/os-release 
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
With uname -a:
4.14.138-114.102.amzn2.x86_64

Docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a215d7133c34aa18e3b72b4a21fd0c6136
 Built:             Mon Jul  1 18:51:44 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a/18.06.1-ce
  Built:            Mon Jul  1 18:53:20 2019
  OS/Arch:          linux/amd64
  Experimental:     false

Show installed: 
sudo rpm -qa '*nvidia*'
libnvidia-container-tools-1.0.0-1.amzn2.x86_64
nvidia-docker2-2.2.2-1.noarch
nvidia-418.87.00-0.amzn2.x86_64
nvidia-dkms-418.87.00-0.amzn2.x86_64
libnvidia-container-1.0.0-1.amzn2.x86_64
nvidia-container-runtime-3.1.4-1.x86_64
nvidia-container-toolkit-1.0.5-2.amzn2.x86_64

[ec2-user@xx ~]$ nvidia-container-cli -V
version: 1.0.0

Using amazon market place image  Amazon Linux 2 AMI with NVIDIA TESLA GPU Driver is using different libraries than your current distributions public repo builders.  

Amazon Linux 2 AMI with NVIDIA TESLA GPU  (tested on p2.xlarge)
Tesla K80 
$nvidia-smi
Wed Oct  2 21:56:41 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.87.00    Driver Version: 418.87.00    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 00000000:00:1E.0 Off |                    0 |
| N/A   61C    P8    32W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                              
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

Then running test of nvidia-smi inside the container actually works: 
[ec2-user@xxx ~]$ sudo docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi
Wed Oct  2 22:00:52 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.87.00    Driver Version: 418.87.00    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 00000000:00:1E.0 Off |                    0 |
| N/A   61C    P8    32W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

**Comment by RenaudWasTaken** [comment]
Hello!

Can you open your issue on https://github.com/NVIDIA/nvidia-docker
It has a pretty detailed issue template that if you filled would allow us to help root cause the issue.

Specifically here your logs point to a driver issue that we would be better able to diagnose if we have the output of `nvidia-container-cli -k -d /dev/tty info`.

**Comment by qingshanyinyin** [comment]
I have encountered the similar problem @JerrettLevensalor, the error is <initialization error: cuda error: unknown error\\\\n\\\"\"": unknown>> !  
![image](https://user-images.githubusercontent.com/35218255/91152439-8a4c8980-e6f1-11ea-9258-1e8b8d9eb977.png)
How to solve it ?  @JerrettLevensalor 
Thanks!
