### ISSUE TITLE
Docker 19 default-runtime: nvidia

### ISSUE THREAD

**Issue by jamesdbrock** [NVIDIA/nvidia-container-runtime#86]
In Docker 18 it was possible to configure the NVIDIA runtime as the default runtime.

https://github.com/NVIDIA/nvidia-container-runtime#daemon-configuration-file

> You can optionally reconfigure the default runtime by adding the following to /etc/docker/daemon.json:
>
> ```
> "default-runtime": "nvidia"
> ```

How can we configure the NVIDIA runtime as the default runtime in Docker 19?

Reference: #12

**Comment by triblex** [comment]
Exact same way for docker 19
