### ISSUE TITLE
Cannot install RPMs in FIPS mode

### ISSUE THREAD

**Issue by zvonkok** [NVIDIA/nvidia-container-runtime#87]
RPMs are missing the payload digest. The packages can only be installed when using 
`rpm -ivh --nodigest --nofiledigest *.rpm` 

```
rpm --checksig -v nvidia-container-runtime-hook-1.4.0-2.x86_64.rpm 
nvidia-container-runtime-hook-1.4.0-2.x86_64.rpm:
    Header V4 RSA/SHA512 Signature, key ID ac1160cd: NOKEY
    Header SHA1 digest: OK
    Payload SHA256 digest: NOTFOUND
    V4 RSA/SHA512 Signature, key ID ac1160cd: NOKEY
    MD5 digest: NOTFOUND
```

This also applies to the dependent packages of `nvidia-container-runtime-hook`.

**Comment by elezar** [comment]
@zvonkok is this still an issue? 

Note that this is related to the `nvidia-container-runtime-hook` package which is no longer being published. I am therefore closing this issue, but please reopen if it is still valid or present in any up to date packages.
