### ISSUE TITLE
key mismatch

### ISSUE THREAD

**Issue by jaymzh** [NVIDIA/nvidia-container-runtime#88]
They repo metadata for 18.04 is signed by `6ED91CA3AC1160CD` - but the keyfiles in the instructions contain the key `DDCAE044F796ECB0`. There doesn't seem to be any place to acquire the `6ED91CA3AC1160CD` key.

**Comment by yzs981130** [comment]
https://github.com/NVIDIA/nvidia-docker/issues/1081

This should work.

**Comment by jaymzh** [comment]
That does not work. As I mentioned in the original, the `wget`s in the documentation (and repeated in that ticket) download `DDCAE044F796ECB0`. But there's no way to acquire the `6ED91CA3AC1160CD` key that I can find.

**Comment by nvjmayo** [comment]
The instructions at https://nvidia.github.io/libnvidia-container/ appear up to date. I see two keys in the file. 
```
$ curl https://nvidia.github.io/libnvidia-container/gpgkey |  gpg --list-packets --verbose  | grep keyid:
        keyid: DDCAE044F796ECB0
        keyid: 6ED91CA3AC1160CD
```

We'll be updating this soon as it expires 2020-09-18.

closing.
