### ISSUE TITLE
nvidia-xconfig not found

### ISSUE THREAD

**Issue by targs08** [NVIDIA/nvidia-container-runtime#93]
I require `nvidia-xconfig` for generate `xorg.conf` configuration inside the container, but command not found. 

docker host has `nvidia-xconfig` binary
```shell
$ ls -1 /run/nvidia/driver/usr/bin/nvidia-xconfig
/run/nvidia/driver/usr/bin/nvidia-xconfig
```
but not available inside container with all capabilities(`NVIDIA_DRIVER_CAPABILITIES=all`)
```
$ ls -1 /usr/bin/nvidia-*
/usr/bin/nvidia-cuda-mps-control
/usr/bin/nvidia-cuda-mps-server
/usr/bin/nvidia-debugdump
/usr/bin/nvidia-persistenced
/usr/bin/nvidia-smi
```
How can automatic mount `nvidia-xconfig`  to container with nvidia runtime?

**Comment by RenaudWasTaken** [comment]
Hello!

This is an unusual request, can you give us more information on your use case?
An easy workaround is to mount that binary in your container.

Thanks!

**Comment by targs08** [comment]
@RenaudWasTaken, thank you for your attention to my issue.

> can you give us more information on your use case?
I wanted to generate Xorg configuration after running the container. I didn't want to depend on any host dependency. 

>  An easy workaround is to mount that binary in your container.
I did it this way. My main idea was doing it without specific mount options. 
As a result, I have decided to create specific entrypoint.
