### ISSUE TITLE
What is the roadmap for nvidia-docker?

### ISSUE THREAD

**Issue by paroque28** [NVIDIA/nvidia-container-runtime#94]
I have seen three main projects you are working on:
- Nvidia-docker (don't know if it is the same as nvidia-docker2)
- container-toolkit
- nvidia-container-runtime

What I want to know is which of these three is the one that will be available in the future. 
As I understand and assume nvidia-container-runtime is being deprecated right? (With the new docker version that allows Native GPU support)

I ask this because I want to create a recipe for Nvidia containers runtime for Yocto and I want to choose the latest technology so that I don't need to replicate work in the future.

Should I use nvidia-docker,  container-toolkit or nvidia-container-runtime for this matter?
I already have libnvidia-container working on yocto.

Thanks,
Pablo

CC : @RenaudWasTaken

**Comment by paroque28** [comment]
If anyone is curious, from my understanding:

Docker uses `nvidia-container-runtime` runtime -> which calls `nvidia-container-toolkit` (or `nvidia-container-runtime-hook` in the past) -> which then calls `libnvidia-container-tools` -> which finally gets to `libnvidia-container`

And then `nvidia-docker` is for older versions of docker

**Comment by RenaudWasTaken** [comment]
Hello!

Sorry for being late:
- `nvidia-docker` is old and deprecated, it install `nvidia-container-runtime`.
- `nvidia-container-runtime` is old and deprecated, but still needed in the Kubernetes context. It installs `nvidia-container-toolkit`.
- `nvidia-container-toolkit` is new and allows you to use `--gpus`, it installs `libnvidia-container-tools`
- `libnvidia-containers-tools` installs `libnvidia-container1`, it is likely that in the future we merge these packages.
