### ISSUE TITLE
Support RHEL8 / CentOS8

### ISSUE THREAD

**Issue by qhaas** [NVIDIA/nvidia-container-runtime#95]
Please consider adding support for Red Hat Enterprise Linux 8 (RHEL8) and/or CentOS8 by building RPMs targeting said environment and hosting them in this project's YUM/DNF repository.  This was mentioned in #79, but likely deserves its own issue.

**Comment by RenaudWasTaken** [comment]
Hi there!

This is already possible :)

**Comment by qhaas** [comment]
> This is already possible :)

You are correct, support has been added, thanks.  I was going by the [documentation](https://nvidia.github.io/nvidia-container-runtime/) that shows the latest supported EL version is 7.
