### ISSUE TITLE
nvidia-container-runtime has broken docker 

### ISSUE THREAD

**Issue by fernkeepvillage** [NVIDIA/nvidia-container-runtime#98]
Something has gone very wrong - I messed around with nvidia-docker and nvidia-container-runtime before deciding I would scrap the project. I uninstalled the packages but I suspect something has gone wrong in the uninstallation because now I can't run docker _at all, for any project_.

```
$ docker pull busybox
Using default tag: latest
latest: Pulling from library/busybox
e2334dd9fee4: Pull complete 
Digest: sha256:a8cf7ff6367c2afa2a90acd081b484cbded349a7076e7bdf37a05279f276bc12
Status: Downloaded newer image for busybox:latest
docker.io/library/busybox:latest
v$ docker run busybox
docker: Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v1.linux/moby/9edb60d72636b96f8ccf2addf8a4f47cae601c4d7e4ca678f6b8cab51a0cbafb/log.json: no such file or directory): exec: "nvidia-container-runtime": executable file not found in $PATH: unknown.
ERRO[0000] error waiting for container: context canceled 
```
I don't know why `docker run` is trying to look for nvidia-container-runtime... how do I properly uninstall this package?

**Comment by bradcornford** [comment]
Did you remove the runtime from you service and daemon?

```
sudo rm /etc/systemd/system/docker.service.d/override.conf
sudo rm /etc/docker/daemon.json
sudo systemctl daemon-reload
sudo systemctl restart docker
```

**Comment by elezar** [comment]
@fernkeepvillage were you able to solve your issue here? (the most likely reason for this failure is that the `nvidia-container-runtime` was specified as your default runtime in `/etc/docker/daemon.json`). I am closing this issue, but please reopen it if you are still having problems.
