### ISSUE TITLE
docker-compose runtime=nvidia with env NVIDIA_VISIBLE_DEVICES OCI runtime create failed

### ISSUE THREAD

**Issue by bradcornford** [NVIDIA/nvidia-container-runtime#99]
It appears whenever i try and add the environment variable NVIDIA_VISIBLE_DEVICES (with any option) to my docker-compose using the runtime=nvidia i receive the following error:

```
OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 1 caused \\\"error running hook: signal: segmentation fault (core dumped), stdout: , stderr: \\\"\"": unknown
```

Running:
Centos: CentOS Linux release 7.8.2003 (Core)
Docker: Docker version 19.03.9, build 9d988398e7
Docker-Compose: docker-compose version 1.25.0, build 0a186604
Nvidia-Container-Runtime: nvidia-container-runtime.x86_64 3.2.0-1

```docker run -e NVIDIA_VISIBLE_DEVICES=all nvidia/cuda:10.0-base nvidia-smi```

```
Tue May 19 14:08:51 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.82       Driver Version: 440.82       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro P2000        Off  | 00000000:01:00.0 Off |                  N/A |
| 68%   36C    P0    18W /  75W |      0MiB /  5057MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

```

**Comment by klueska** [comment]
We are aware of this issue and should have a patch release out later today. In the meantime, please downgrade to the previous version.

**Comment by bradcornford** [comment]
I downgraded `yum downgrade nvidia-container-runtime` and still faced the issue. Is there something else i should downgrade?

**Comment by klueska** [comment]
New packages have been published that should resolve this issue. Please run one of the following depending on your platform:

```
sudo apt-get install nvidia-container-toolkit
```
```
sudo yum install nvidia-container-toolkit
```

If you originally installed `nvidia-docker2` and not `nvidia-container-toolkit`, you should still run the commands above in order to update `nvidia-docker2` properly (it has a dependence on `nvidia-container-toolkit` that will now be upgraded).

**Comment by bradcornford** [comment]
Thanks, that looks to be working now.
